### ISSUE TITLE
🐛 Bug: Kanban drag drop issue

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#8306] opened 2024-04-20 12:18 UTC
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="860" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/84ef4c34-512c-4141-9199-e5ad1af79ff7">

### Desired Behavior

.

### Project Details

.

**Comment by dstala** [comment] 2024-04-21 02:42
tried on v0.205.1 with PG as rootDB. couldn't reproduce.

**Comment by imtg-suitecrm** [comment] 2024-04-21 16:31
Hi @dstala here are some more details. 

We are also using PG and it's happening every single time. 

<img width="1135" alt="3-kanban error" src="https://github.com/nocodb/nocodb/assets/26126325/afc13240-83e4-48e4-a32f-f00dc03b312b">
<img width="1145" alt="2-kanban default view" src="https://github.com/nocodb/nocodb/assets/26126325/c6f0b603-b8b3-4018-b9c9-8a899b6c7132">
<img width="1148" alt="1-milestone fields" src="https://github.com/nocodb/nocodb/assets/26126325/d6e92a11-edca-4ce2-8619-77a6849ffe1c">

**Comment by imtg-suitecrm** [comment] 2024-04-24 16:33
Hey @dstala is there anything else I can provide you with that might help get to the bottom of this issue we are seeing? 

Alternatively, how would we go about getting you credentials to the test environment where the error is reproducible 100% of the time for us, so it helps the team's troubleshooting efforts? 

This issue with the kanban is a show stopper for our use case and we'd love to help try and get it fixed :) 

Thank you in advance.

**Comment by dstala** [comment] 2024-05-29 01:05
@imtg-suitecrm there are few related fixes gone in recently. could you let us know if the issue is still reproducible at your end?

**Comment by imtg-suitecrm** [comment] 2024-05-31 04:28
Thank you @dstala - yes confirmed fixed on the latest version that we just tried. Thank you very much.

**Comment by dstala** [comment] 2024-05-31 04:47
@imtg-suitecrm thanks for that update. will close this issue

**Closed by dstala** 2024-05-31 04:47 UTC
