### ISSUE TITLE
🐛 Bug: nc-help module does not have a main

### ISSUE THREAD

**Issue by dni300** [nocodb/nocodb#4323] opened 2022-11-08 12:43 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

entrypoint of dockerfile: /usr/src/appEntry/start.sh
yields:
```
  node:internal/modules/cjs/loader:372
        throw err;
        ^
  
  Error: Cannot find module '/usr/src/app/node_modules/nc-help/index.js'. Please verify that the package.json has a valid "main" entry
      at tryPackage (node:internal/modules/cjs/loader:364:19)
      at Function.Module._findPath (node:internal/modules/cjs/loader:577:18)
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
      at Function.Module._load (node:internal/modules/cjs/loader:804:27)
      at Module.require (node:internal/modules/cjs/loader:1028:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (/usr/src/app/docker/main.js:1:13738)
      at a (/usr/src/app/docker/main.js:1:352)
      at Object.<anonymous> (/usr/src/app/docker/main.js:1:113471)
      at a (/usr/src/app/docker/main.js:1:352) {
    code: 'MODULE_NOT_FOUND',
    path: '/usr/src/app/node_modules/nc-help/package.json',
    requestPath: 'nc-help'
  }
```

### Desired Behavior

started application

### Project Details

NocoDB used as docker: true
NocoDB version: latest
Database used: mssql

**Comment by mertmit** [comment] 2022-11-12 11:16
Can you please share which version have you try, is this a local build, if so which steps did you take for this build?

**Comment by dni300** [comment] 2022-11-13 19:40
No it's just the current "latest" docker image - version 0.98.4.
I got it to work by running as entry point override:
`
tar -xzf /usr/src/appEntry/app.tar.gz -C /usr/src/app/ && \
apk add npm && \
npm i @azure/msal-node && \
npm i mssql && \
npm audit fix && \
npm i nc-help@0.2.67 && \
node docker/main.js
`
So it seems the default docker image still has some issues.

**Comment by wingkwong** [comment] 2023-02-13 10:05
Closing - couldn't reproduce the issue - probably resolved at some point - feel free to reopen if necessary.

**Closed by wingkwong** 2023-02-13 10:05 UTC
Labels: 👩‍🔬 Status: In-Analysis
