### ISSUE TITLE
[vue3] project title & project menu drop down icon spills over tabs

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3196] opened 2022-08-17 04:34 UTC
![Screenshot 2022-08-17 at 10 03 06 AM](https://user-images.githubusercontent.com/86527202/185035391-f388681d-0169-4660-92f7-3c97c1ed12c5.png)

**Comment by bcakmakoglu** [comment] 2022-08-17 09:08
duplicate of #3173

**Closed by bcakmakoglu** 2022-08-17 09:08 UTC
Labels: Scope: vue3
