### ISSUE TITLE
🔦 Feature: Pressing tab while on a form should move the cursor to the next field

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#5969] opened 2023-06-27 09:41 UTC
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently, when you are filling out a NocoDB form, when you press tab, the cursor jumps to the "Submit" button. This is can be annoying as in most other applications tab moves the cursor to the next input field.

### Suggested Solution

When you press tab, your cursor should move to the next form field instead of all the way down to the "Submit" button.

**Comment by cppchriscpp** [comment] 2023-09-05 22:08
Just to add, this is also an accessibility issue. Users who can't use a mouse (example: blind users) likely cannot fill out a form currently.

**Comment by okaeiz** [comment] 2023-12-06 14:47
Is this going to be fixed in the future?

**Comment by dstala** [comment] 2023-12-06 15:11
@okaeiz yes. we will try to pick this up as soon as we can. use of tab to navigate works for few field types, but the need to support this for all field types increases implementation work.

**Comment by dstala** [comment] 2024-01-17 05:52
works in v0.204.0; any issue if seen, report here with associated field type & reopen this thread

**Closed by dstala** 2024-01-17 05:52 UTC
Labels: Status: Reproducible

**Comment by cppchriscpp** [comment] 2024-01-17 06:16
Confirmed this works for me! Thank you!
