### ISSUE TITLE
npm start on dashboard showing 404 Not Found

### ISSUE THREAD

**Issue by raitman005** [nocodb/nocodb#3047] opened 2022-08-09 02:22 UTC
Did use the npx create-nocodb-app with sqlite with node.js project setting then hit the npm start tried to visit the url of mywebsite/dashboard the result is Not Found got the error of TextEncoder is not defined. I'm lost now and can't find answers where to change or fix.

**Comment by wingkwong** [comment] 2022-08-12 08:02
Just tested and couldn't reproduce the issue. It'd be great if you could give the following info.

1. What is your node version?
2. `npm install; npm run start` is executed automatically. At which step did you see the error? 
3. Could you provide the whole error log?

**Comment by dstala** [comment] 2022-12-29 08:56
@raitman005 closing this issue for now; please reopen if you see issue persists with latest release

**Closed by dstala** 2022-12-29 08:56 UTC
Labels: 🔎 Status: More Info Needed
