### ISSUE TITLE
URL abstract type should support URI schemes

### ISSUE THREAD

**Issue by ghostwalkerj** [nocodb/nocodb#469] opened 2021-08-17 23:52 UTC
Many applications have URI schemes or application custom URLs associated with them.  For example, each email message can have a unique URL.  Additionally there are applications which allow the dynamic creation of custom links such as [Hook](https://hookproductivity.com/). This is very useful as it allows the storage of links to documents, email messages, chat messages and on.

The current URL abstract type fails the validation of application links.  This should be changed to allow all valid application links to be stored in the column and to **open the link when clicked**.

Here is a list of valid [URI schemes](https://en.wikipedia.org/wiki/List_of_URI_schemes).  Should be trivial to validate with a regex.

**Comment by Zuoqiu-Yingyi** [comment] 2021-11-23 08:33
I think so, too.
It is also important to note that there are many URL Schemes of Apps that are not registered.
For example, the following table lists Apps.
- Zotero
- Marginnote
- BookxNote
- OneNote
- Obsidian
- SiYuan
- Craft
- Bear
- OmniFocus
- Things
- Devonthink
- Everything
- Alfred
- Evernote
- iThoughts
- Agenda
- org-roam
- Simplenote

**Comment by jpbourgeon** [comment] 2022-03-24 08:50
This is a duplicate of #746

**Closed** 2023-09-01 04:49 UTC
Labels: ✨ Type: Enhancement, 🔦 Type: Feature, 👋 For : Community or Good First Issue, 🍰 Scope : Column
