### ISSUE TITLE
🐛 Bug: json Column → returning null, errors in console, won't save

### ISSUE THREAD

**Issue by Rafurus** [nocodb/nocodb#4484] opened 2022-11-24 15:02 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create json column. Try to add json or other text. 
2. Try to edit field after refreshing page. 
3. Try to open modal to edit field after refreshing page. 

### Desired Behavior

After creating JSON column i try to add some json. First of all field was set to null and i couldn't edit this. After some refreshing i could add json. Next time when i was trying to edit field modal was totally empty. I console i found error when modal was open. 

### Project Details

Version: 0.99.0
Docker: true
DB: pq

### Attachements

![obraz](https://user-images.githubusercontent.com/12428720/203814236-afdfc40e-3bfa-4d6e-bdd1-123deec782ed.png)
![obraz](https://user-images.githubusercontent.com/12428720/203814254-957b9a3b-c476-4101-9a3a-1e5a38be3d0a.png)
![obraz](https://user-images.githubusercontent.com/12428720/203814273-d683b9b2-3fdf-4ecc-aeb2-2ac7e2e46714.png)
![obraz](https://user-images.githubusercontent.com/12428720/203814901-d0334b70-411a-4a5f-a594-35e490f12bc8.png)

**Comment by wingkwong** [comment] 2022-11-25 08:55
Seems I couldn't reproduce the issue. Could you mind to record it?

[json-demo](https://user-images.githubusercontent.com/35857179/203940166-3c053ca1-535e-411b-90fe-0efc7f40246e.webm)

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.99.0**
```

**Comment by wingkwong** [comment] 2023-01-07 04:00
Closing it as

- Not reproducible
- No further feedback

**Closed by wingkwong** 2023-01-07 04:00 UTC
Labels: 🔎 Status: More Info Needed
