### ISSUE TITLE
🐛 Bug: Previous project table count is shown in current project

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4028] opened 2022-10-12 10:44 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Observed with db with large amount of tables (500+)
- 

### Desired Behavior

-Should the right amount of rows

### Project Details

- 0.97.0

**Comment by wingkwong** [comment] 2022-10-13 04:43
From discord:

https://discord.com/channels/661905455894888490/661905455894888493/threads/1029683977969217546

**Comment by wingkwong** [comment] 2023-01-07 03:46
Closing it as 

- Not able to reproduce and 
- No further feedback from user

**Closed by wingkwong** 2023-01-07 03:46 UTC
