### ISSUE TITLE
🔦 Feature: Tooltip Description for Table Columns

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#8892] opened 2024-06-28 13:40 UTC
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Implement a feature that allows users to see a brief description of a column when hovering over it with the mouse.

- **Improved User Experience:** Users receive immediate contextual information about the table contents, simplifying usage.
- **Efficiency:** Reduces the need for additional documentation by providing key information directly.

#### Requirements:
1. **Tooltip Display:** When the mouse hovers over the header of a table column, a tooltip with a description of the column should appear.
2. **Custom Descriptions:** The description texts should be individually configurable for each column.
3. **Styling:** Tooltips should be uniformly and user-friendly designed to blend well with the existing software design.
4. **Placement and Behavior:** Tooltips should appear immediately when the mouse pointer hovers over a column and disappear when the pointer leaves the column.
5. **Performance:** The new functionality should not impact the application’s performance.

#### Acceptance Criteria:
- A descriptive tooltip appears when hovering over a column header with the mouse.
- Tooltips contain clear and concise information that can be defined by the administrator settings.
- Tooltips disappear when the mouse pointer leaves the column header.
- The software’s performance remains unaffected by this feature.

### Additional Context

This enhancement will significantly improve the user-friendliness and efficiency of our software.

**Comment by salim-b** [comment] 2024-06-28 20:18
Duplicate of https://github.com/nocodb/nocodb/issues/7665.

**Closed** 2024-08-17 13:37 UTC
