### ISSUE TITLE
🔦 Feature: Support LinkToAnotherRecord with CSV import

### ISSUE THREAD

**Issue by drbryce** [nocodb/nocodb#5146] opened 2023-02-17 17:36 UTC
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

I have a spreadsheet that I'm converting to a database. I have columns where there's a finite set of options that I'd like to have come from another table. 

For example, I want to import data into a table that contains information about different product configurations. I want a column in that table to be a LTAR that points to a table containing product names instead of using a text or single select data type.

### Suggested Solution

This would be handled with additional options to select when using the quick import tool and defining how the columns in the CSV match up to the table columns.

**Comment by bbock** [comment] 2023-09-19 07:07
I guess this is a duplicate of #3803

**Comment by dstala** [comment] 2023-11-03 11:24
To be tracked along with https://github.com/nocodb/nocodb/issues/3803

**Closed by dstala** 2023-11-03 11:24 UTC
