### ISSUE TITLE
Anyone encountered data not properly saving in UI?

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#1813] opened 2022-04-21 10:05 UTC
### Discussed in https://github.com/nocodb/nocodb/discussions/1812

<div type='discussions-op-text'>

<sup>Originally posted by **RawmanGrey** April 21, 2022</sup>
While I was playing around NocoDB UI testing cases for the issue, quite unpleasant thing happened: data I was entering was not always properly saved and was disappearing on page updates. This issue I was able to reproduce running test docker setup with `docker run -p 8080:8080 -d nocodb/nocodb` command. So the question is, am I alone with this?) 

<details> 
  <summary>recorded bug as .gif</summary>

![Peek 2022-04-21 12-43](https://user-images.githubusercontent.com/61871501/164430926-51c167f7-6718-405a-89e4-7cf77dbc778e.gif)
</details></div>

**Comment by o1lab** [comment] 2022-04-21 10:08
I can see on entering numbers its not getting saved.

Could you share your project info from right top.

**Comment by o1lab** [comment] 2022-04-21 10:19
What browser are you on ?

**Comment by RawmanGrey** [comment] 2022-04-21 10:29
Data type doesn't matter. If data is entered in table view it can be not saved. 

Just tested, it has nothing to do with SSL. And yes, this is browser related. I'm on Firefox Dev 99.0b8 64bit. No issues on my Chromium.

**Comment by o1lab** [comment] 2022-04-21 10:58
@mertmit

**Comment by mertmit** [comment] 2022-04-21 20:36
Thanks for detailed bug report.
This issue seem to caused by blur event not firing by Firefox if you save rows with ENTER key which is going to be fixed with PR.

**Comment by cj-wong** [comment] 2022-04-22 04:40
I noticed this issue by coincidence. I'm almost certain it's the same bug I've had in issue #1637. I'm glad that a root cause was found! I'll be sure not to use the Enter key when updating my data. I'll also close my issue.

**Closed** 2022-04-23 10:15 UTC
Labels: Type: Bug, Status: Fixed
