### ISSUE TITLE
Problem with SingleSelect Column

### ISSUE THREAD

**Issue by stepanof** [nocodb/nocodb#2059] opened 2022-05-16 17:34 UTC
Hi team!

I have a problem with tables which contain SingleSelect column.

```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.90.11**
```

**Steps To Reproduce**

1. Create new table
2. Create new column (choose type = SingleSelect, create a couple possible options, NOT NULL)
![image](https://user-images.githubusercontent.com/68236577/168646641-c1e65267-b89f-45ac-9b93-aba01f4bf56d.png)

4. Create new row and try to choose value for created Column
5. ### See that it is impossible to choose value because it doesn't exist
![image](https://user-images.githubusercontent.com/68236577/168646667-27636041-f07c-458c-adee-44dcb38752fd.png)

**Expected Behavior**

After creation of new Column with options there must be possibility to select values fot columns with SingleSelect type.

**Comment by wingkwong** [comment] 2022-05-17 05:16
Any error message you can share? I'm not able to reproduce the issue following the steps you provided.

![image](https://user-images.githubusercontent.com/35857179/168734377-dccb848c-aa21-4272-b772-1356f3118727.png)

**Comment by wingkwong** [comment] 2022-05-18 03:49
@stepanof Can you try again with node version >= 14.18.0?

**Comment by o1lab** [comment] 2022-05-18 18:02
The nodejs version is baked in and cant be changed  - you are right.
What is the postgres version you are using ? that migth give us some clue.

**Comment by wingkwong** [comment] 2022-05-19 03:39
I believe this issue has been resolved in some commits. 

0.90.11 Docker Version - Reproducible
Local - Not reproducible 
Local Docker version (nocodb-daily) - Not reproducible

**Closed** 2022-05-23 11:27 UTC
Labels: Status: Resolved
