### ISSUE TITLE
🐛 Bug: PDF files in chinese names can not be previewed

### ISSUE THREAD

**Issue by Hirriririir** [nocodb/nocodb#9129] opened 2024-08-01 04:18 UTC
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Dear Developers,

Great work!

I tried to upload some PDFs named in Chinese characters ('胸腺.pdf') to my self-hosted NocoDB, but it showed "Failed to Load PDF document."
![image](https://github.com/user-attachments/assets/7ffaab26-95c5-4042-9749-7a3a7860926e)

I realized that this might be related to a language encoding problem. I then renamed the file to "xiongxian.pdf," and NocoDB was able to display the file correctly.

![image](https://github.com/user-attachments/assets/12b92ef3-e20e-4b9d-8ca8-324054c46020)

By the way, this is not a problem for PNG files. Could you please fix this? Thank you!

Best,

Hua

### Desired Behavior

PDF preview supports files named in other languages.

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.251.3**

**Comment by DarkPhoenix2704** [comment] 2024-08-01 18:32
hey @Hirriririir, WIll you be able to provide a sample file. 

We couldnt reproduce this in our end

**Comment by Hirriririir** [comment] 2024-08-11 01:53
@DarkPhoenix2704 Thanks for your reply!

I found this seems to be a single case. Other PDFs with Chinese characters work fine in NocoDB.

**Comment by DarkPhoenix2704** [comment] 2024-08-11 03:35
Seem the PDF is an corrupted one. Closing this issue

**Closed by DarkPhoenix2704** 2024-08-11 03:35 UTC
Labels: 🐛 Type: Bug
