### ISSUE TITLE
When I try to choose a value in a many-to-many relationship NocoDB's interface doesn't show me options.

### ISSUE THREAD

**Issue by lcfd** [nocodb/nocodb#2523] opened 2022-07-01 09:11 UTC
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **true**
RootDB: **pg**
PackageVersion: **0.92.0**
```

**Steps To Reproduce**

1. Go to a table with a linked field to another table with a many-to-many relationship
2. Add a new row
3. Try to pick a value in the many-to-many column
4. No options are available

```
msg: "... where ((((\"created_at\" ilike '%%%%')))) order by \"id\" asc limit 10 - operator does not exist: timestamp without time zone ~~* unknown"
```

**Expected Behavior**

The other table is full of records so I expect to see values to choose from below the `filter query` input box.

**Screenshots**

![CleanShot 2022-07-01 at 11 04 20](https://user-images.githubusercontent.com/9001053/176863415-4c1d288d-a142-4200-9057-38e44ff28791.png)

![CleanShot 2022-07-01 at 10 59 26](https://user-images.githubusercontent.com/9001053/176862237-65973607-90b1-4df2-8347-a776312efffc.png)

Thank you!

**Comment by mertmit** [comment] 2022-07-01 12:05
This is about having non-text field in like condition (CreatedAt) related with #2517 fix should be applicable for both

**Comment by justinmayer** [comment] 2022-07-04 11:03
I have also run into this issue, which OP has documented very well. (Bravo, OP!)

Could a maintainer add this issue to the [next milestone](https://github.com/nocodb/nocodb/milestone/8), with the intention of ensuring this problem is addressed in the next bug-fix update?

**Comment by mertmit** [comment] 2022-07-05 17:29
@lcfd Is it possible for you to confirm if this resolved on develop branch (or if you prefer docker/executables you can use the ones provided #2531) as I couldn't reproduce the exact case

**Closed** 2022-07-16 09:33 UTC
Labels: Status: Resolved
