### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by Rednas83** [nocodb/nocodb#850] opened 2021-12-10 11:19 UTC
**Need for this feature**
Are there plans for a better view for small screens like phones/tablets?

**Is your feature request related to a problem? Please describe.**
Currently NocoDB on a mobile looks like this
![image](https://user-images.githubusercontent.com/25219229/145565929-0ceb7a5a-b3cc-4d21-804b-4a4415cb4f77.png)

**Comment by gemurdock** [comment] 2021-12-12 03:02
Progressive web app? :)

**Comment by Rednas83** [comment] 2021-12-12 08:47
Not perse, more like responsive. The idea of mobile first
* Hide the menu behind a button for small screens
* Make the spreadsheet fullscreen for small screens

Something like:
![image](https://user-images.githubusercontent.com/25219229/145706084-fb676634-aa8e-4da5-b517-bc8f38a586f5.png)

**Comment by Morakhiyasaiyam** [comment] 2022-04-15 04:36
+1

**Comment by louwers** [comment] 2022-06-03 19:46
Duplicate of #158

**Comment by o1lab** [comment] 2022-09-11 21:57
Tracked in #158

**Closed by o1lab** 2022-09-11 21:57 UTC
Labels: Type: Feature
