### ISSUE TITLE
🐛 Bug: Error occurs when copy to clipboard

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8338] opened 2024-04-25 03:19 UTC
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Although there are several issues described this error, but it still exists. I responsed in https://github.com/nocodb/nocodb/issues/5333,  but may because this issue has been closed, there is no reply,so I open a new issue.
 This bug still exists in version **0.205.1**. My test steps are as follows, hope can provide some infos for you to target this issue.
**[Environment]**
- Windows VS code development enviroment.
- with "pnpm run watch:run" command to run the project.

**[steps]**
- Access "http://localhost:port" . Can copy nomally.
![image](https://github.com/nocodb/nocodb/assets/48933981/ec2167a8-d95f-45d7-b132-c7334536be56)
- Access "http://127.0.0.1:port" .Can copy nomally,too.
![image](https://github.com/nocodb/nocodb/assets/48933981/4b235c37-4609-4ba5-b027-b5ed3e86eae0)
- Access "http://IP:port". It goes wrong!
![image](https://github.com/nocodb/nocodb/assets/48933981/a8665fce-1603-467b-85aa-a7ba423cd2c2)
![image](https://github.com/nocodb/nocodb/assets/48933981/e48f4fde-8409-4c0f-9257-f293951f0435)

Looking forward to your reply！

### Desired Behavior

x

### Project Details

development

**Comment by o1lab** [comment] 2024-04-25 06:03
Hey, thanks for the detailed error report. I understand this issue is happening in development mode? Any reason why are you using ip address and can you pls debug on what is the error in fronted.

**Comment by Omnimercador** [comment] 2024-04-25 08:05
Experiencing the same situation. In our case, we access our NocoDB instance via a domain name/dynamic public ip address and via port forwarding to the server. 

Notably, copying of multiple cells 
- only works when on 127.0.0.1  (i.e. by implication on the server)
- it does not work when I use the LAN IP in a browser **on the server**

**Comment by mertmit** [comment] 2024-04-25 18:34
Thank you for the detailed issue report; I was able to debug and reproduce using the information you provided.

The reason was that the clipboard property is disabled for insecure contexts (non-HTTPS places other than localhost) by browsers. (Reference: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard)

<img width="788" alt="Screenshot 2024-04-25 at 21 30 53" src="https://github.com/nocodb/nocodb/assets/59797957/7ca67072-eece-40a7-bddb-0c3d05af7007">

This should be fixed with our next release.

**Comment by TangXY123** [comment] 2024-04-26 08:33
@o1lab @mertmit Thank you for responsing! I will also debug this in version 0.205.1. 
Looking forward the new version~

**Closed** 2024-04-28 03:13 UTC
Labels: 👀 Status: In Review
