### ISSUE TITLE
🐛 Bug: Adding attachment leads to error "Cannot set properties of null (setting 'Sortable1713167698240')".

### ISSUE THREAD

**Issue by TangXY123** [nocodb/nocodb#8278] opened 2024-04-15 08:24 UTC
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- If one table have an "attachment" Field, and meanwhile we upload a file in this field. After click from this attachment-table to **other base's table,** it throws out an error. "Cannot set properties of null (setting 'Sortable1713167698240')"

**Here are the logs:**
message: Cannot set properties of null (setting 'Sortable1713168699264')

TypeError: Cannot set properties of null (setting 'Sortable1713168699264')
    at p.destroy (http://localhost:8080/dashboard/_nuxt/sortable.esm.BS5toX6s.js:6:28780)
    at http://localhost:8080/dashboard/_nuxt/index.DlUt09iI.js:2:9364
    at Hs (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:14886)
    at I.onStop (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:25353)
    at yd.stop (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:5617)
    at mx.stop (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:4293)
    at xe (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:59797)
    at re (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:59024)
    at xe (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:59822)
    at re (http://localhost:8080/dashboard/_nuxt/entry.D5PpQrY8.js:1:59024)

![image](https://github.com/nocodb/nocodb/assets/48933981/7057102a-ba10-4813-8af8-564f46f47732)

**Additional infos：**
- For non-Admin users， this error throws out directly.
- For Admin user, this error shows after we log out the system. But not eachtime this error shows(I don't know why,May be click for more times will repreduce)
![image](https://github.com/nocodb/nocodb/assets/48933981/391df67a-5f3e-4f15-b677-2d96020ecf6f)

### Desired Behavior

x

### Project Details

version: 0.205.1
db: sqlite\mysql8.0
environment: docker\development

### Attachments

Testing video.
https://github.com/nocodb/nocodb/assets/48933981/9182c468-6d73-474b-8941-69f877d19e4e

**Comment by dstala** [comment] 2024-04-16 05:18
- unable to reproduce. tried with both pg & mysql
- we can look into error attached along with to see if that helps

**Comment by mertmit** [comment] 2024-05-13 07:25
@dstala This might be fixed by https://github.com/nocodb/nocodb/pull/8416

**Closed** 2024-05-15 09:51 UTC
Labels: Status: Reproducible
