### ISSUE TITLE
Users not displayed

### ISSUE THREAD

**Issue by eevleevs** [nocodb/nocodb#1351] opened 2022-02-24 08:18 UTC
Using MSSQL, on "Team and Auth" the user list is empty. In the console I get:

`TypeError: this.selectedUser.roles.split is not a function`

_Screenshot - added by @wingkwong_
![image](https://user-images.githubusercontent.com/35857179/155651334-72230867-21fc-4e8e-8516-a1d70fa5ebde.png)

**Comment by wingkwong** [comment] 2022-02-24 09:46
@eevleevs I couldn't reproduce this issue. Please provide your Project Info (here's the [step](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-)) and and some more details.

Project Info Example:

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mssql**
ProjectOnRootDB: **false**
RootDB: **sqlite3**
PackageVersion: **0.84.12**

**Comment by eevleevs** [comment] 2022-02-24 09:48
Node: **v12.22.6**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mssql**
ProjectOnRootDB: **true**
RootDB: **mssql**
PackageVersion: **0.84.12**

**Comment by wingkwong** [comment] 2022-02-24 10:31
Tried using the same node version and still not able to reproduce this issue. Please DM me in Discord.

**Comment by eevleevs** [comment] 2022-02-24 15:32
> Semi-Reproduced (didn't get an error, just nothing listed)

@RachelAmbler My error is in the console (press ctrl+shift+I)

**Comment by wingkwong** [comment] 2022-02-24 16:12
@RachelAmbler Are you also using MSSQL? Also having the same error in browser console?

**Comment by dstala** [comment] 2023-02-03 07:02
@RachelAmbler closing this Issue as it was observed on a very older baseline. If you still see this issue with newer release, please reopen.

**Closed by dstala** 2023-02-03 07:02 UTC
Labels: 🔎 Status: More Info Needed, 🥅 DB : MSSQL
