### ISSUE TITLE
🔦 Feature: Specific Roles to Access to specific tables

### ISSUE THREAD

**Issue by Shahin-rmz** [nocodb/nocodb#5692] opened 2023-05-21 21:03 UTC
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Hi,
NocoDB is awesome in order to liberating and democratizing Nocode solutions for companies.
There are cases, that we want to give two colleagues A and B, separate tables. TA and TB.
The thing is, both A and B have same roles but working on different tables.
So we should separate their access to the data that is visible to them.

### Suggested Solution

[APITable](https://help.apitable.com/docs/guide/manual-mirror/) has a solution, which is mirroring.
This mirror thing, can make a view, and give it access to one certain colleague.
The colleague can have any roles, with different permissions.

### Additional Context

This is very helpful when two same colleagues work on different tasks which should not be mixed up.

**Comment by davidbuzz** [comment] 2023-05-31 01:23
dupe of https://github.com/nocodb/nocodb/issues/2712

**Comment by wingkwong** [comment] 2023-05-31 02:39
Duplicate - see above link

**Closed by wingkwong** 2023-05-31 02:39 UTC
