### ISSUE TITLE
🐛 Bug: Memory crash when importing large base from Airtable

### ISSUE THREAD

**Issue by itay-sgh** [nocodb/nocodb#4649] opened 2022-12-11 15:16 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Trying to import a base consists of 3 tables each table around ~35k rows with ~120 fields each. 
It crashed after reading all the records from the first table during "Importing". 
I've monitored the container stats and memory get's very high and crashes.

```
pg-nocodb-1   | <--- Last few GCs --->
pg-nocodb-1   | 
pg-nocodb-1   | [12:0xffff8868a3f0]  1861388 ms: Scavenge (reduce) 7803.6 (8238.2) -> 7803.4 (8238.2) MB, 36.8 / 0.0 ms  (average mu = 0.386, current mu = 0.497) allocation failure 
pg-nocodb-1   | [12:0xffff8868a3f0]  1861429 ms: Scavenge (reduce) 7804.3 (8238.2) -> 7804.1 (8238.2) MB, 37.5 / 0.0 ms  (average mu = 0.386, current mu = 0.497) allocation failure 
pg-nocodb-1   | [12:0xffff8868a3f0]  1889033 ms: Scavenge (reduce) 7805.1 (8238.2) -> 7804.9 (8238.7) MB, 27596.0 / 0.0 ms  (average mu = 0.386, current mu = 0.497) allocation failure 
pg-nocodb-1   | 
pg-nocodb-1   | 
pg-nocodb-1   | <--- JS stacktrace --->
pg-nocodb-1   | 
pg-nocodb-1   | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
pg-nocodb-1   | Aborted
```

### Desired Behavior

Handle large bases and keep importing.

### Project Details

nocodb docker image on Mac M1
nocodb version 0.100.2
NODE OPTIONS: --max_old_space_size=8192
Docker resources:
CPUs - 5
Memory - 9GB
Swap - 4GB

**Comment by mertmit** [comment] 2023-08-30 08:39
Seems like a duplicate of https://github.com/nocodb/nocodb/issues/4650 which is resolved.
Feel free to raise an issue again if issue persist for you.

**Closed by mertmit** 2023-08-30 08:39 UTC
Labels: 🐛 Type: Bug
