### ISSUE TITLE
🐛 Bug: when I import a csv file,I ge a 404 error

### ISSUE THREAD

**Issue by TangYoulong** [nocodb/nocodb#4648] opened 2022-12-10 16:32 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1、import a csv file

### Desired Behavior

1、I get a 404 error
![image](https://user-images.githubusercontent.com/47670867/206864937-e30d6491-6051-4f51-b0f6-9bb9721718a6.png)

and when I  open response msg, I get Data truncated for column '状态' at row 1"
![image](https://user-images.githubusercontent.com/47670867/206864974-774db57c-d0b8-4bfa-bd7d-47eb88f2d4b8.png)

### Project Details

version:0.100.2

**Comment by wingkwong** [comment] 2022-12-10 16:54
Please provide a csv file for reproducing the issue. It seems there is some invalid data.

**Comment by wingkwong** [comment] 2023-01-07 04:07
Closing due to no feedback from user.

**Closed by wingkwong** 2023-01-07 04:07 UTC
Labels: 🔎 Status: More Info Needed
