### ISSUE TITLE
Deleting of user not possible

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#1399] opened 2022-03-02 19:46 UTC
Node: **v12.22.6**
Arch: **x64**
Platform: **linux** (QNAP 5.0.0.1932)
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2** (MariaDB 10.5.8)
PackageVersion: **0.84.14**

**Steps To Reproduce**
1. Go to 'Team & Auth' 
2. Create a new user (in this case `owner`)
3. Send invitation
4. Try to delete the user by clicking the trash bin - there still is the name and you still can copy the invitation link

**Expected behavior**
After deleting an user the name should disappear an entries should be cleared.

**Screenshots**
![User delete](https://user-images.githubusercontent.com/20600342/156437959-b3c47c99-2b18-4d73-b3ab-26b8f29ae841.jpg)

If i take a look in database with phpMyAdmin i can see the xc_user still is there.

![phpMyAdmin](https://user-images.githubusercontent.com/20600342/156438773-bcdb2806-995f-4f79-b586-6f11ac7f746c.jpg)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by dstala** [comment] 2022-03-03 04:52
@WeT-Klb 
User entry, we retained it by design as it simplifies the procedure for adding the same user for a different project.
Invite URL needs to be disabled after the user is removed from the project. We will take it up.

**Comment by wingkwong** [comment] 2022-03-04 03:21
Closing it as it is duplicate with #214.

**Closed by wingkwong** 2022-03-04 03:21 UTC
