### ISSUE TITLE
Roll up the formula column failed and make all rows cannot be accessed

### ISSUE THREAD

**Issue by zhang-win** [nocodb/nocodb#1842] opened 2022-04-23 07:01 UTC
NocoDB used as docker : true
NocoDB version : 0.90.5
Database  : mysql 8.0.22
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running :  MacOS 12.3.1
Database version : 

**Steps To Reproduce**
1. create two tables, one is 'tasks', and the other one is 'time log'
2. create a foreign key from tasks to time log
4. create a formula column in 'time log' to calculate the hours between two timestamp
5. in 'tasks' create a rollup column to aggregate the value of the above formula column
6. refresh the page

**Expected behavior**
Aggregate the values of the formula column

**Actual behavior**
Nothing seen in the new rollup column, and after reload the page, no data shown in

**Screenshots**
<img width="1229" alt="截屏2022-04-23 14 55 15" src="https://user-images.githubusercontent.com/37443093/164883933-02fae2b2-0790-42ef-ac72-0849451087ec.png">
<img width="471" alt="截屏2022-04-23 14 56 22" src="https://user-images.githubusercontent.com/37443093/164883942-d1a619c3-ab88-4694-9b3d-38142e44b83f.png">

<img width="647" alt="截屏2022-04-23 14 56 37" src="https://user-images.githubusercontent.com/37443093/164883956-7cf843c2-303b-47dc-9701-d4c88f5cf7d5.png">
<img width="1538" alt="截屏2022-04-23 14 57 47" src="https://user-images.githubusercontent.com/37443093/164883975-2192f3fd-0e35-4bd1-8ae6-e2e2a4f33127.png">
<img width="1345" alt="截屏2022-04-23 14 57 59" src="https://user-images.githubusercontent.com/37443093/164883982-daed8cd4-d724-4608-a519-e36c3dbd040d.png">

Node version : **v12.22.12**
Arch type: **x64**
Platform: **MacOS**
Docker: **true**
Database: **MySQL**

**Comment by wingkwong** [comment] 2022-04-23 07:49
Able to reproduce. 

Formula: `(INT(((end - start) / 10000)) + (MOD((end - start), 10000) / 6000))`

**Comment by o1lab** [comment] 2022-04-23 07:51
@zhang-win / @wingkwong : please paste the error logs from console.

**Comment by wingkwong** [comment] 2022-04-23 07:53
msg: "select (select sum(`issue1842_time_log`.`null`) from `issue1842_time_log` where `issue1842_tasks`.`id` = `issue1842_time_log`.`issue1842_tasks_id`) as `Rollup`, `issue1842_tasks`.`id` as `Id`, `issue1842_tasks`.`title` as `Title`, `issue1842_tasks`.`created_at` as `CreatedAt`, `issue1842_tasks`.`updated_at` as `UpdatedAt` from `issue1842_tasks` where `id` = 3 limit 1 - Unknown column 'issue1842_time_log.null' in 'field list'"

**Comment by wingkwong** [comment] 2022-04-23 09:51
Currently rollup on virtual columns is not supported. `formula` shouldn't be selected in the column list. I'd suggest to subscribe [Support rollup columns on virtual columns](https://github.com/nocodb/nocodb/issues/1844) for the update on this feature.

**Comment by wingkwong** [comment] 2022-04-24 09:11
Closing this issue. Virtual columns are now hid in rollup column list since `v0.90.7`.

**Closed by wingkwong** 2022-04-24 09:11 UTC
Labels: Type: Bug
