### ISSUE TITLE
🐛 Bug: Reverse proxy by nocodb

### ISSUE THREAD

**Issue by lolgopher** [nocodb/nocodb#6147] opened 2023-08-09 01:04 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I want to set up a reverse proxy for nginx and use nocodb. However, some errors occur.

## setting
- nginx.conf
```
location /nocodb/dashboard {
    proxy_pass http://nocodb.default.svc.cluster.local:80/nocodb/dashboard;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /nocodb/ {
    proxy_pass http://nocodb.default.svc.cluster.local:80/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
- nocodb env
```
- name: NC_DASHBOARD_URL
  value: /nocodb/dashboard
- name: NC_PUBLIC_URL
  value: "https://call.kep.dev/nocodb"
- name: NUXT_PUBLIC_NC_BACKEND_URL
  value: "https://call.kep.dev/nocodb"
```
## error case
1. accessing call.kep.dev/nocodb/ 
<img width="714" alt="스크린샷 2023-08-09 오전 9 51 09" src="https://github.com/nocodb/nocodb/assets/34984529/dfba0b23-3b98-464a-ab5d-e268e705de86">

2. open swagger page
<img width="767" alt="스크린샷 2023-08-09 오전 9 58 25" src="https://github.com/nocodb/nocodb/assets/34984529/a2854ad8-67e0-45e5-822f-b9bcba12bcbe">

### Desired Behavior

- All requests are correctly reverse proxy
- No any error

### Project Details

Node: **v16.20.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.109.5**

```
NocoDB used as docker : true
NocoDB version :  0.109.5
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : linux
Node.js version if running as node : v16.20.0
Database version : mysql 5.7.33
```

**Comment by mertmit** [comment] 2023-08-09 01:34
Looks like a duplicate of https://github.com/nocodb/nocodb/issues/1033
Please see if setups provided in this issue help you or try moving to subdomain based proxy setup.

**Comment by lolgopher** [comment] 2023-08-11 06:21
I have to use it as a subdirectory based proxying.

I'm opening a PR for this #6157

**Closed** 2023-08-13 06:18 UTC
Labels: 🐛 Type: Bug
