### ISSUE TITLE
Many-Many relationships don't populate in form/expanded view

### ISSUE THREAD

**Issue by jfacemyer** [nocodb/nocodb#971] opened 2022-01-19 17:56 UTC
Node: **v17.2.0**
Arch: **x64**
Platform: **linux**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.84.6**

**Steps To Reproduce**
1. Create table with many-many relationship to another table.
2. Add records to both tables and link one to the other.
3. Open the form edit ("expand") view, scroll to relationship field.
4. See the emptiness of the relationship field.

**Expected behavior**
The relationship field should show the related records.

**Screenshots**
![image](https://user-images.githubusercontent.com/1776340/150184183-90ad27b5-4352-4cc6-a3e4-c66c2355cc2d.png)

![image](https://user-images.githubusercontent.com/1776340/150184261-00a0106a-8a92-45f1-98f9-b35171729993.png)

**Additional Info**
Console 400 Bad request error:
where | conditionGraph | {"nc_s63f___nc_m2m_nc_s63f__properties_nc_s63f__people":{"relationType":"hm","nc_s63f__people_c_id":{"eq":5}}}

**Comment by wingkwong** [comment] 2022-01-28 09:29
@jfacemyer are you able to reproduce the same issue at ``0.84.8``?

![image](https://user-images.githubusercontent.com/35857179/151521663-adf3f64f-d642-4b52-b40b-8ae137da03c7.png)

![image](https://user-images.githubusercontent.com/35857179/151521571-d93dfe34-8586-4f78-87a1-75b9cc887a24.png)

**Comment by wingkwong** [comment] 2022-03-12 10:58
Couldn't reproduce at latest version as well. Closing it now. Please feel free to reopen if you still have encountered such issue.

**Closed by wingkwong** 2022-03-12 10:58 UTC
Labels: Status: More Info Needed
