### ISSUE TITLE
🐛 Bug: bottom paging navigation hidden/non-functional in shared view at standard resolution

### ISSUE THREAD

**Issue by onejgordon** [nocodb/nocodb#6401] opened 2023-09-17 20:19 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a link to a shared view including 40+ rows
- Visit the view in a new window (no signed in user)
- Note that the paging links at bottom are not visible unless one:
    - Uses a very high res display
    - Zooms way out in the browser
 - Scrolling down does not solve the issue, the page links never appear
 - Result: cannot meaningfully view the table (since no pages other than first can be accessed)

### Desired Behavior

Bottom paging links should be visible in shared views at all times, regardless of screen density.

### Project Details

NocoDB used as docker: false
NocoDB version: 0.111.4
Database used in NC_DB_URL: pg
Project was created by clicking: New Project

### Attachments

<img width="1196" alt="Screenshot 2023-09-17 at 16 10 59" src="https://github.com/nocodb/nocodb/assets/57584/0af3838d-6b21-402f-86a1-97fe033409ec">

**Comment by pranavxc** [comment] 2023-09-18 17:01
Duplicate of https://github.com/nocodb/nocodb/issues/6276

**Comment by wingkwong** [comment] 2023-09-19 03:39
Closing - duplicate

**Closed by wingkwong** 2023-09-19 03:39 UTC
Labels: 🟠 Priority: High, Status: Reproducible
