### ISSUE TITLE
🐛 Bug: Trying to download from NocoDB server instead of Backblaze

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#5914] opened 2023-06-17 11:22 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Upload a file via any view to a record. 
2. Then with some chance, when you try to download the file, nothing will happen and the error described below will occur. 

The issue seems to occur at random.

A video has been shared privately with the core team.

## Details

**Browser Logs**
```
XHRHEAD
https://REDACTED/nc/uploads/noco/REDACTED/Pitch Deck PDF/REDACTED.pdf
[HTTP/2 404 Not Found 25ms]

TypeError: URL constructor: /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf is not a valid URL.
    NuxtJS 6
ant-design-vue.25ebc081.js:1:14464
```

**NocoDB Logs**
```
Jun 17 10:58:39 [Nest] 1 - 06/17/2023, 10:58:39 AM ERROR [i] Cannot HEAD /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf
Jun 17 10:58:39 NotFoundException: Cannot HEAD /nc/uploads/noco/REDACTED/REDACTED.pdf
Jun 17 10:58:39 at /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:23
Jun 17 10:58:39 at /app/code/node_modules/express/lib/router/index.js:286:9
Jun 17 10:58:39 at Function.process_params (/app/code/node_modules/express/lib/router/index.js:346:12)
Jun 17 10:58:39 at Layer.handle [as handle_request] (/app/code/node_modules/express/lib/router/layer.js:95:5)
Jun 17 10:58:39 at callback (/app/code/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
Jun 17 10:58:39 at next (/app/code/node_modules/express/lib/router/index.js:280:10)
Jun 17 10:58:39 at next (/app/code/node_modules/express/lib/router/route.js:136:14)
Jun 17 10:58:39 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 10:58:39 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 10:58:39 at trim_prefix (/app/code/node_modules/express/lib/router/index.js:328:13)
Jun 17 10:59:37 [Nest] 1 - 06/17/2023, 10:59:37 AM ERROR [i] Cannot HEAD /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf
Jun 17 10:59:37 NotFoundException: Cannot HEAD /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf
Jun 17 10:59:37 at /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:23
Jun 17 10:59:37 at /app/code/node_modules/express/lib/router/index.js:286:9
Jun 17 10:59:37 at Function.process_params (/app/code/node_modules/express/lib/router/index.js:346:12)
Jun 17 10:59:37 at Layer.handle [as handle_request] (/app/code/node_modules/express/lib/router/layer.js:95:5)
Jun 17 10:59:37 at callback (/app/code/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
Jun 17 10:59:37 at next (/app/code/node_modules/express/lib/router/index.js:280:10)
Jun 17 10:59:37 at next (/app/code/node_modules/express/lib/router/route.js:136:14)
Jun 17 10:59:37 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 10:59:37 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 10:59:37 at trim_prefix (/app/code/node_modules/express/lib/router/index.js:328:13)
Jun 17 11:02:41 [Nest] 1 - 06/17/2023, 11:02:41 AM ERROR [i] Cannot HEAD /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf
Jun 17 11:02:41 NotFoundException: Cannot HEAD /nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf
Jun 17 11:02:41 at /app/code/node_modules/@nestjs/core/router/router-proxy.js:9:23
Jun 17 11:02:41 at /app/code/node_modules/express/lib/router/index.js:286:9
Jun 17 11:02:41 at Function.process_params (/app/code/node_modules/express/lib/router/index.js:346:12)
Jun 17 11:02:41 at Layer.handle [as handle_request] (/app/code/node_modules/express/lib/router/layer.js:95:5)
Jun 17 11:02:41 at callback (/app/code/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
Jun 17 11:02:41 at next (/app/code/node_modules/express/lib/router/index.js:280:10)
Jun 17 11:02:41 at next (/app/code/node_modules/express/lib/router/route.js:136:14)
Jun 17 11:02:41 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 11:02:41 at next (/app/code/node_modules/express/lib/router/route.js:140:7)
Jun 17 11:02:41 at trim_prefix (/app/code/node_modules/express/lib/router/index.js:328:13)
```

**Additional Comments**

- The broken records always refer to a non existent file in local NocoDB blob storage ex. `https://REDACTED/nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf`
- If I replace the base url with our B2 Bucket location, then I **can** access the file: `https://REDACTED.s3.us-west-004.backblazeb2.com/nc/uploads/noco/REDACTED/Pitch%20Deck%20PDF/REDACTED.pdf`
- It seems like NocoDB is sometimes just assigning the wrong host when generating the URL for download in the UI

### Desired Behavior

The files should download correctly when clicked on 100% of the time.

### Project Details

```
Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.1**
```

The DB was created using the Airtable import tool offered by NocoDB.

**Comment by 3699n** [comment] 2023-06-17 11:22
@pranavxc Created a issue corresponding to our conversation

**Comment by salim-b** [comment] 2024-03-18 21:18
I'm experiencing the same issue.
- It happens reproducibly.
- The data source doesn't seem to matter, it happens both with tables in an external PostgreSQL database as well as tables in NocoDB's default data source (SQLite).
- It only happens for files **above a certain size, I think around 5 MiB**.
  - For smaller files, the generated links are fine, i.e. point to the B2/S3 bucket.
  - For larger files, relative links without the hostname are generated, i.e. they lack the `https://<BUCKET_NAME>.s3.<BUCKET_REGION>.backblazeb2.com` prefix.

This is a really annoying issue. 😐

### Workaround

My current workaround is the following trigger function created in the external PostgreSQL database:

```sql
--- Create function and trigger to fix NocoDB attachment URLs
CREATE OR REPLACE FUNCTION public.fix_attachments_url()
  RETURNS TRIGGER AS $$
  BEGIN
    NEW.attachments = regexp_replace(NEW.COLUMN_NAME, '"url":"/nc/uploads/', '"url":"https://BUCKET_NAME.s3.BUCKET_REGION.backblazeb2.com/nc/uploads/', 'g');
    RETURN NEW;
  END;
  $$ language 'plpgsql';

CREATE OR REPLACE TRIGGER set_attachments_url
  BEFORE INSERT OR UPDATE OF "COLUMN_NAME" ON public.TABLE_NAME
  FOR EACH ROW EXECUTE PROCEDURE public.fix_attachments_url();
```

(Replace `TABLE_NAME`, `COLUMN_NAME`, `BUCKET_NAME` and `BUCKET_REGION` with the actual strings that apply to your setup.)

This workaround works as intended. I only need to refresh the page after inserting new attachments that exceed the 5 MiB size limit to be properly displayed/clickable in NocoDB.

**Comment by divemasterza** [comment] 2024-06-04 14:37
I can confirm same -> attachements over 5MB generate a 
`Cannot HEAD /nc/uploads/noco/xx/xxxxxx/xxxxxxx/xxxx.mp4` error

quite critical for proper functionality

**Comment by DarkPhoenix2704** [comment] 2024-08-02 06:09
Fixed in https://github.com/nocodb/nocodb/pull/9104

**Closed by DarkPhoenix2704** 2024-08-02 06:09 UTC
