### ISSUE TITLE
Can't configure self signed SSL certificate for Digital Ocean Postgres

### ISSUE THREAD

**Issue by flobaader** [nocodb/nocodb#324] opened 2021-07-05 14:11 UTC
Hi,

is it possible to configure NocoDB with a self signed SSL database (like the postgres provided by DigitalOcean)?

![image](https://user-images.githubusercontent.com/16624361/124484260-84acdf00-ddab-11eb-9075-70221c21929e.png)

**This is my current config**

```json
{
  "client": "pg",
  "connection": {
    "host": "HOST",
    "port": "PORT",
    "user": "USER",
    "password": "PASSWORD",
    "database": "DB",
    "ssl": "true",
  }
```

**The knex docs suggest the following approach**

```json
{
   "ssl" : {
    "rejectUnauthorized": "false" // this does not work
  }

}
```

**This is also not working**

```json
{
    "rejectUnauthorized": "false" // this does not work
}
```

NocoDB used as docker : true
NocoDB version : 
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created :  pg

**Comment by o1lab** [comment] 2021-07-05 14:18
Using knexjs could you make a successful connection to this dB and let us know what helped. There is an issue open for ssl it might be duplicate of this 

There was another user faced issue with digital ocean. See latest discussions in github. I guess it's not the same in your case though.

**Comment by flobaader** [comment] 2021-07-07 06:53
Okay I solved my problem by adding the following env var to the nocodb container
`NODE_TLS_REJECT_UNAUTHORIZED: "0"` 

One strange behavior is that I cannot use "non-ssl" databases now, as nocodb always tries to use SSL for each database.

**Comment by o1lab** [comment] 2021-07-07 09:01
```
NODE_TLS_REJECT_UNAUTHORIZED: "0"
```

Ah, remember encountering this for another customer.

Found this : https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain

**Comment by guzmonne** [comment] 2021-11-30 16:26
For me the solution was to configure the `connection` object like this:

```json
"connection": {
    "host": "",
    "port": "",
    "user": "",
    "password": "",
    "database": "",
    "ssl": {
      "rejectUnauthorized": false,
      "ca": "-----BEGIN CERTIFICATE----- ..."
    }
}
```

Basically, configure the `ca` value inside the `ssl` configuration.

**Comment by sudermanjr** [comment] 2022-03-25 18:08
Can verify, that works for me in the connection JSON

**Comment by dstala** [comment] 2023-11-01 11:16
@flobaader if you still have some issues, do reopen this thread. I hope the solution provided by @pranavxc helps here

**Closed by dstala** 2023-11-01 11:16 UTC
Labels: 🐘 DB : Postgres
