### ISSUE TITLE
🐛 Bug: Upload to Backblaze B2 Provider Not Working Occasionally

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4896] opened 2023-01-21 00:23 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Occasionally when trying to upload a file to a record, the file isn't actually uploaded. It is shown as being uploaded on the UI with the thumbnail being displayed, but nothing happens when trying to download the file or open it in a new window. The thumbnail and file name remains in the record after saving. I notice this issue occasionally and it seems to occur occasionally in any view type (Form, Grid View, etc.). There is no feedback in the UI indicating that the upload has failed.

I have been using the Backblaze B2 storage provider for many months, and noticed that this issue occurs from time to time.

![image](https://user-images.githubusercontent.com/7414843/213828322-1babe20b-2e7e-4f66-8b52-41e9afb5bf60.png)

```
Jan 21 00:15:40 r [Error]: Column not found
Jan 21 00:15:40 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:40 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:40 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:40 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:40 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:40 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:40 r [Error]: Column not found
Jan 21 00:15:40 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:40 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:40 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:40 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:40 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:40 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:40 T :: o [Error]: Internal Server Error, check server log for more details
Jan 21 00:15:40 at t.NcError.internalServerError (/app/code/node_modules/nocodb/dist/bundle.js:1:18947)
Jan 21 00:15:40 at /app/code/node_modules/nocodb/dist/bundle.js:1:1617291
Jan 21 00:15:40 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:40 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:40 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:40 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91/group/undefined 500 66 - 45.927 ms
Jan 21 00:15:45 GET /api/v1/db/meta/kanbans/vw_7wishohwztjo91 200 - - 13.922 ms
Jan 21 00:15:45 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91?offset=0&limit=25&where=(Startup+Name,like,%25bettoeroff%25) 200 98 - 53.563 ms
Jan 21 00:15:45 r [Error]: Column not found
Jan 21 00:15:45 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:45 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:45 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:45 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:45 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:45 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:45 r [Error]: Column not found
Jan 21 00:15:45 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:45 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:45 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:45 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:45 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:45 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:45 T :: o [Error]: Internal Server Error, check server log for more details
Jan 21 00:15:45 at t.NcError.internalServerError (/app/code/node_modules/nocodb/dist/bundle.js:1:18947)
Jan 21 00:15:45 at /app/code/node_modules/nocodb/dist/bundle.js:1:1617291
Jan 21 00:15:45 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:45 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:45 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:45 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91/group/undefined 500 66 - 26.312 ms
Jan 21 00:15:48 GET /api/v1/db/meta/kanbans/vw_7wishohwztjo91 200 - - 34.443 ms
Jan 21 00:15:48 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91?offset=0&limit=25&where=(Startup+Name,like,%25bettoeoff%25) 200 98 - 57.500 ms
Jan 21 00:15:49 r [Error]: Column not found
Jan 21 00:15:49 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:49 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:49 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:49 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:49 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:49 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:49 r [Error]: Column not found
Jan 21 00:15:49 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:49 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:49 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:49 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:49 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:49 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:49 T :: o [Error]: Internal Server Error, check server log for more details
Jan 21 00:15:49 at t.NcError.internalServerError (/app/code/node_modules/nocodb/dist/bundle.js:1:18947)
Jan 21 00:15:49 at /app/code/node_modules/nocodb/dist/bundle.js:1:1617291
Jan 21 00:15:49 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:49 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:49 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:49 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91/group/undefined 500 66 - 27.454 ms
Jan 21 00:15:50 GET /dashboard 301 185 - 4.991 ms
Jan 21 00:15:53 GET /api/v1/db/meta/kanbans/vw_7wishohwztjo91 200 - - 31.183 ms
Jan 21 00:15:53 GET /api/v1/db/data/noco/p_xigvfcuzfn6rq1/md_r239ic6rr25fxp/views/vw_7wishohwztjo91?offset=0&limit=25&where=(Startup+Name,like,%25bettoroff%25) 200 2482 - 150.416 ms
Jan 21 00:15:53 r [Error]: Column not found
Jan 21 00:15:53 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:53 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:53 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:53 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:53 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:53 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:53 r [Error]: Column not found
Jan 21 00:15:53 at t.NcError.notFound (/app/code/node_modules/nocodb/dist/bundle.js:1:18769)
Jan 21 00:15:53 at t.BaseModelSqlv2.groupedList (/app/code/node_modules/nocodb/dist/bundle.js:1:1272081)
Jan 21 00:15:53 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:53 at async /app/code/node_modules/nocodb/dist/bundle.js:1:1616790
Jan 21 00:15:53 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:53 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
Jan 21 00:15:53 T :: o [Error]: Internal Server Error, check server log for more details
Jan 21 00:15:53 at t.NcError.internalServerError (/app/code/node_modules/nocodb/dist/bundle.js:1:18947)
Jan 21 00:15:53 at /app/code/node_modules/nocodb/dist/bundle.js:1:1617291
Jan 21 00:15:53 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 21 00:15:53 at async T (/app/code/node_modules/nocodb/dist/bundle.js:1:1616366)
Jan 21 00:15:53 at async /app/code/node_modules/nocodb/dist/bundle.js:1:18140
```

### Desired Behavior

The file should be uploaded correctly, such that it can be downloaded again afterwards.

### Project Details

```
Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.101.2**
```

**Comment by wingkwong** [comment] 2023-01-21 03:43
1. If the actual file is not uploaded to Backblaze but is still able to show in UI, what would the download link be? Is it still pointing to backblaze? 
2. From the error message, it says Column not found. May I know what column types you have in the problematic table?  
3. Did the error message show after uploading or clicking download button?

**Comment by 3699n** [comment] 2023-01-21 03:54
@wingkwong 
1. According the a different error message I just receive from the JS console after clicking on the broken thumbnail, the url points to `/nc/uploads/noco/SFF%20Dealflow/Sourcing/Pitch%20Deck%20PDF/REDACTED.pdf`

This is the full error from the JS console:
```
TypeError: URL constructor: /nc/uploads/noco/SFF%20Dealflow/Sourcing/Pitch%20Deck%20PDF/REDACTED.pdf is not a valid URL.
    NuxtJS 5
ant-design-vue.35dd57df.js:4:1162
```
2. Please refer to the ERD diagram below for the table types.
![image](https://user-images.githubusercontent.com/7414843/213842215-c2caf965-fbee-42c4-ba52-1d8a6eb47263.png)

3. The error I shared in my initial bug report was shown in the Server logs after **uploading**. The log I shared in 2. was shown in the JS console after trying to download.

**Comment by wingkwong** [comment] 2023-01-21 04:02
For the broken thumbnails, did you upload the attachments before setting up Backblaze? 

For the uploading issue, will investigate.

**Comment by 3699n** [comment] 2023-01-21 04:02
No the attachments were uploaded just today.

**Comment by 3699n** [comment] 2023-01-21 04:03
I just manually checked the B2 bucket, and `REDACTED.pdf` does exist. So it seems like it might just be an issue with the link in the UI or how the URL to the PDF it is saved after it is uploaded to B2. The thumbnail seems to be linking to a broken link with the with the `https://XXX-XXX-XXX.s3.us-west-00X.backblazeb2.com` part missing before the rest of the URL ` /nc/uploads/noco/SFF+Dealflow/Sourcing/Pitch+Deck+PDF/REDACTED.pdf`

**Comment by wingkwong** [comment] 2023-01-21 04:31
Both seems unexpected and weird and need time to investigate.

For the url part, `url` is returned directly from the client upon successful upload.

For `Column not found` error, it is triggered in `groupedList` while it shouldn't be triggered during upload.

**Comment by wingkwong** [comment] 2023-01-21 08:18
@3699 three more questions.

- when you upload the attachment, is it on a grid view?
- when you upload the attachment, is it on a shared view?
- does your table contain kanban view?

**Comment by 3699n** [comment] 2023-01-21 15:35
@wingkwong 
1. Yes I tried to uploaded by search for the record on the grid view and the uploading it in the detailed view. However, I am certain this issue has occured on multiple different vies including the Form view.
2. Sometimes. Regardless of if it is uploaded via the private grid view or via the shared Form view, the error occasionally occurs for both.
3. Yes. The table has a grid, kanban, and form view.

**Comment by 3699n** [comment] 2023-02-07 22:15
@wingkwong Have you been able to identify the source of the issue. The error is still occurring for me from time to time when new files are uploaded.

**Comment by wingkwong** [comment] 2023-02-13 09:25
Not really. Does it only happen to the same table? Have you tried it on other tables?

**Comment by 3699n** [comment] 2023-02-16 19:01
I haven't tried it on other tables, or at least not been able to reproduce it, because it only seems to be an issue for about 5-10% of rows.

**Comment by 3699n** [comment] 2023-02-22 14:59
@wingkwong Could the issue be related to the project being imported from Airtable? About 80% of the rows are imported from Airtable and the remaining 20% were created within NocoDB. Since you import the schema from Airtable (which is quite different from the NocoDB default ex. the primary key types), maybe this is causing some form of inconsistency, especially when combed with the B2 plugin?

**Comment by 3699n** [comment] 2023-02-22 15:02
The initial Airtable import also never fully succeeded (meaning that while all Rows were presents, the attachments from Airtable had not all been fully uploaded, even though they were shown to have been in the attachments view).

**Comment by 3699n** [comment] 2023-02-23 14:52
@wingkwong Now I can't access any of the documents saved in NocoDB following this updates.
I receive the following error when trying to click on a file in NocoDB:
![image](https://user-images.githubusercontent.com/7414843/220941928-00963cd6-6b1e-44fd-b15f-1107b2387d2c.png)

```
Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.105.3**
```

**Comment by salim-b** [comment] 2024-03-18 20:50
> According a different error message I just received from the JS console after clicking on the broken thumbnail, the url points to `/nc/uploads/noco/SFF%20Dealflow/Sourcing/Pitch%20Deck%20PDF/REDACTED.pdf`
> (...)
> I just manually checked the B2 bucket, and `REDACTED.pdf` does exist. So it seems like it might just be an issue with the link in the UI or how the URL to the PDF it is saved after it is uploaded to B2. The thumbnail seems to be linking to a broken link with the with the `https://XXX.s3.us-west-00X.backblazeb2.com` part missing before the rest of the URL ` /nc/uploads/noco/SFF+Dealflow/Sourcing/Pitch+Deck+PDF/REDACTED.pdf`

I think this issue is a duplicate of https://github.com/nocodb/nocodb/issues/5914.

**Comment by divemasterza** [comment] 2024-06-04 14:55
happens only of the files is larger the 5MB. 

Larger than that the file uploads but cannot be retrieved 
`Cannot HEAD /nc/uploads/noco/xx/xxxxxx/xxxxxxx/xxxx.mp4` error

**Comment by DarkPhoenix2704** [comment] 2024-08-02 06:09
This issue is fixed in https://github.com/nocodb/nocodb/pull/9104

Will be available in next release

**Closed by DarkPhoenix2704** 2024-08-02 06:09 UTC
Labels: 🐛 Type: Bug, 👩‍🔬 Status: In-Analysis
