### ISSUE TITLE
🐛 Bug: Impossible to input data to a single select column type in form

### ISSUE THREAD

**Issue by ilyak0** [nocodb/nocodb#5939] opened 2023-06-21 10:54 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Any form in any database after the last update just collapses the single select field on click
https://github.com/nocodb/nocodb/assets/111974217/c0d33e30-28de-485b-aedc-6dde6b8b953a

### Desired Behavior

Should allow the choice

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.109.1**

**Comment by pranavxc** [comment] 2023-06-21 14:13
Duplicate of https://github.com/nocodb/nocodb/issues/5926

Fix is part or our latest release - `0.109.2`

**Closed by pranavxc** 2023-06-21 14:13 UTC
