### ISSUE TITLE
🐛 Bug: Duplicated user entries showing up

### ISSUE THREAD

**Issue by emre1e** [nocodb/nocodb#4264] opened 2022-11-02 14:25 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

http://{ip}/api/v1/db/meta/projects/{Project_id}/users?limit=10&offset=0&query=

Output : 10 Users

http://{ip}/api/v1/db/meta/projects/{Project_id}/users?limit=10&offset=10&query=

Output: 10 Users but some are already in the first ouput.

The Offset seems to work wrong.

### Desired Behavior

In the Tab Team & Auth users showing up duplicated.

The Offset seems to work wrong.

### Project Details

Docker: Yes
Database: pg
Version: 0.98.3

**Comment by emre1e** [comment] 2022-11-03 12:11
i found the issue. On the file https://github.com/nocodb/nocodb/blob/08d73677dc6e794babe930edd8b54e2dc465434f/packages/nocodb/src/lib/models/ProjectUser.ts#L79-L94
The order by clause missing.
If im right it should be something like:

const queryBuilder = ncMeta
      .knex(MetaTable.USERS).**orderBy(`${MetaTable.USERS}.id`)**
      .select(
        `${MetaTable.USERS}.id`,
        `${MetaTable.USERS}.email`,
        `${MetaTable.USERS}.invite_token`,
        `${MetaTable.USERS}.roles as main_roles`,
        `${MetaTable.PROJECT_USERS}.project_id`,
        `${MetaTable.PROJECT_USERS}.roles as roles`
      )
      .offset(offset)
      .limit(limit);

**Comment by wingkwong** [comment] 2022-11-15 03:05
I couldn't reproduce the issue on the latest version (0.98.4). Could you help double confirm it? 

I created 12 new users.

Page 1:
![image](https://user-images.githubusercontent.com/35857179/201816220-e4504ae6-1b83-40ee-a151-2cb131917f3c.png)

Page 2:
![image](https://user-images.githubusercontent.com/35857179/201816257-3e6e4595-a797-4f08-b153-2b98033c535d.png)

About adding `orderBy`:

```
const queryBuilder = ncMeta
.knex(MetaTable.USERS).orderBy(${MetaTable.USERS}.id)
.select(
${MetaTable.USERS}.id,
${MetaTable.USERS}.email,
${MetaTable.USERS}.invite_token,
${MetaTable.USERS}.roles as main_roles,
${MetaTable.PROJECT_USERS}.project_id,
${MetaTable.PROJECT_USERS}.roles as roles
)
.offset(offset)
.limit(limit);
```

I don't think adding `orderBy` here is a good idea as the format of the user id is like `us_xxxxxxxxxxxxx`. Just an arbitrary random string instead of a numeric value.

**Comment by emre1e** [comment] 2022-11-15 12:54
even in the sql its not working. Maybe its because of postgresql. 
if you excecute this in PSQL you will see the duplicated entries. Just change the offset.

14 Users in this Project(nc_project_users_v2)
48 Users in Total(nc_users_v2)

select nc_users_v2.id, nc_users_v2.email, nc_users_v2.roles 
from nc_users_v2 left join nc_project_users_v2 On nc_users_v2.id = nc_project_users_v2.fk_user_id
and nc_project_users_v2.project_id = '@project_id'
LIMIT 10
OFFSET 0

**Comment by wingkwong** [comment] 2022-11-15 15:46
Could you please record a video on the latest version? Using the SQL you provided returns the correct result.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/35857179/201962785-d187fe5f-d254-4ff6-8f90-e1ace18f0fed.png">

<img width="413" alt="image" src="https://user-images.githubusercontent.com/35857179/201962733-a6e7845e-3336-4239-9955-2b851ae97638.png">

**Comment by emre1e** [comment] 2022-11-15 16:09
![image](https://user-images.githubusercontent.com/117290601/201968764-bdc685f7-18f4-439b-9bd0-43c4c3f47e4c.png)
![image](https://user-images.githubusercontent.com/117290601/201968878-e4bac42a-70fd-4a2c-9e38-c6472c97d5e3.png)
![image](https://user-images.githubusercontent.com/117290601/201968965-ce15e76c-3aa0-45fa-89fe-390a3b807aa8.png)

**Comment by wingkwong** [comment] 2022-11-15 16:16
which user id are repeating?

**Comment by emre1e** [comment] 2022-11-16 11:29
Just look first one and last one. there are many duplicated. Its default behaviour on tables without primary tables. If i put in a order by clause, everything starts to work perfectly.

**Comment by wingkwong** [comment] 2022-12-06 05:41
Following your query but still don't see duplicate records on latest version. Can you try it on latest version as well as on a new project?

<img width="671" alt="image" src="https://user-images.githubusercontent.com/35857179/205825532-9ddec2ab-3ef2-44e5-9b5a-d24c0b11d97f.png">

<img width="689" alt="image" src="https://user-images.githubusercontent.com/35857179/205825573-c592b220-fccb-4c58-95fb-0042a3bff870.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/35857179/205825620-1932eaa8-d4f9-4743-beb0-96bdefad52a3.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/35857179/205825651-f0da5070-8af7-4f84-aaf7-f9cd69158e11.png">

**Comment by wingkwong** [comment] 2023-01-07 03:58
Closing it as 

- Not reproducible 
- No further feedback

**Closed by wingkwong** 2023-01-07 03:58 UTC
Labels: Status: Not Reproducible
