### ISSUE TITLE
Facing issue while using Monaco editor present in Nocodb

### ISSUE THREAD

**Issue by AztrexDX** [nocodb/nocodb#331] opened 2021-07-07 10:57 UTC
Hi,

I have been trying to use MonacoTsEditor present in Nocodb as code editor instead of normal textarea. Facing below issue while using it
![image](https://user-images.githubusercontent.com/86340924/124745086-0da75000-df3d-11eb-9633-8c27a3502541.png)

I have used it as below:
- import the editor
![image](https://user-images.githubusercontent.com/86340924/124745210-32032c80-df3d-11eb-980c-e9dc3f971768.png)
- include in component
![image](https://user-images.githubusercontent.com/86340924/124745299-49dab080-df3d-11eb-9ca6-409d5a90e69f.png)
- use it
![image](https://user-images.githubusercontent.com/86340924/124745346-5959f980-df3d-11eb-91f0-b44f51186bf4.png)

I tried debugging and found may be web workers are not loading correctly.
Currently temporary workaround I am using it is to comment the model initialization. But then code color doesn't come and few features are removed.
![image](https://user-images.githubusercontent.com/86340924/124746646-befab580-df3e-11eb-845d-b102a023a6fb.png)

Overall I am trying to add abstract type code editor where I can store code snippets

There is also warning comes when activating few other monaco editor like sql
![image](https://user-images.githubusercontent.com/86340924/124747260-5fe97080-df3f-11eb-82f7-3bfc3107e77c.png)

It doesn't cause issue in execution but too many cause lag in ui

Steps to produce(both for ts and sql editor):
- Implement it
- Error comes in console when it is activated

Node: **v14.15.1**
Arch: **x64**
Platform: **win32**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.9.41**

**Comment by o1lab** [comment] 2021-07-08 07:31
hey 😅 - thanks for trying our SQL Editor. We'd it disabled as of now :) But you could double click on Audit and get it 😉

I see it works, I was able to run a query. See attached.

<img width="1138" alt="Screen Shot 2021-07-08 at 12 59 57" src="https://user-images.githubusercontent.com/5435402/124881129-9fba6180-dfec-11eb-806f-d0be35b75493.png">

**Comment by drdomark** [comment] 2021-07-09 10:48
Yes sql editor works, even monacots editor works. Main issue I had been facing is while using Monacotseditor the vue wrapper created around Monoca editor. The issue is below when tying to use it. The component works but this issue when occurs too much causes lag in browser. I have given steps of how I have implemented it and possible issue I think.
![image](https://user-images.githubusercontent.com/50301882/125065331-50009680-e0cf-11eb-803b-6074352b9bfa.png)

In case of sql editor I just reported the issue that language prop is already present is coming in console. In case you are seeing it then you may fix it.

I had been developing my own airtable like alternative for past year with Java backend and angular for some use case. I have been going through nocodb to see how much design and implementation wise I did correct. I am implementing few use case in nocodb and checking. So that's why while checking I reached sql editor and other monaco editor implementation.

**Comment by AztrexDX** [comment] 2021-07-09 10:55
Yes sql editor works, even monacots editor works. Main issue I had been facing is while using Monacotseditor the vue wrapper created around Monoca editor. The issue is below when tying to use it. The component works but this issue when occurs too much causes lag in browser. I have given steps of how I have implemented it and possible issue I think.
image
![image](https://user-images.githubusercontent.com/86340924/125067716-3d3b9100-e0d2-11eb-959c-fa23c03e7258.png)


In case of sql editor I just reported the issue that language prop is already present is coming in console. In case you are seeing it then you may fix it.

I had been developing my own airtable like alternative for past year with Java backend and angular for some use case. I have been going through nocodb to see how much design and implementation wise I did correct. I am implementing few use case in nocodb and checking. So that's why while checking I reached sql editor and other monaco editor implementation.

**Comment by o1lab** [comment] 2021-08-21 08:24
This is a out of scope for time being as this is custom implementation.

We'll borrow the notes from here when using monaco/

**Closed by o1lab** 2021-08-21 08:24 UTC
