### ISSUE TITLE
🐛 Bug: Unable to enter text on form after interacting with single select field

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#5968] opened 2023-06-27 09:38 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When trying to fill out a NocoDB form, if you interact with a single select field by clicking on it once, whenever you then try to enter text anywhere else in the form, the cursor focus will keep jumping back to the single select field. [Video demo](https://drive.google.com/file/d/1gQqplJFKnngY7ILIFaTNyFO9wq10qNC2/view?usp=sharing)

1. Interact with a single select field in the form
2. Try to enter text into any other input field

The issue occurs on both chrome and firefox.

### Desired Behavior

The cursor focus should not always jump to the single select field.

### Project Details

Node: **v18.12.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.109.2**

**Comment by pranavxc** [comment] 2023-07-22 07:16
Looks like a duplicate of https://github.com/nocodb/nocodb/issues/5926. To resolve the problem please upgrade to the latest version.

**Closed by pranavxc** 2023-07-22 07:16 UTC
Labels: Status: Reproducible
