### ISSUE TITLE
🐛 Bug: API Url mixes between project Id, project name in Swagger, doc ...

### ISSUE THREAD

**Issue by Productivix** [nocodb/nocodb#6187] opened 2023-08-16 17:07 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1.  go to the **dashbord** and on 1 table for ex : "effective_whitefish/Sc_Etat_stock" , ex you get the url : "mydomain/dashboard/#/nc/p_cjsn1eu1rph25b/table/md_sot0dt2fm355w2" : we use a project Id , not name
2.  in **Swagger**, you get : "mydomain/api/v1/db/data/v1/effective_whitefish/Sc_Etat_stock?..." that gives a 200 status with an error : "Undocumented | TypeError: NetworkError when attempting to fetch resource.  We use project name but does not work
4. in the "Get table row"  **documentation**, on https://apis.nocodb.com/#tag/DB-Table-Row/operation/db-table-row-read, you have the url : "http://localhost:8080/api/v1/db/data/{orgs}/{projectName}/{tableName}/" ,  where {orgs} = "noco" 

### Desired Behavior

so :
 What is the good url composition please ? There is too much documentation different or means not upgraded at the same time that gives different results or mainly no results !

### Project Details

Node: **v18.14.2**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.109.7**

**Comment by wingkwong** [comment] 2023-08-17 09:27
Supposedly they are interchangeable and both should return the same result. Using names would be convenient for better readability.  For the second point, can you take a screenshot or shot a short video to show how to reproduce the issue?

**Comment by Productivix** [comment] 2023-08-18 10:08
hi, thank you for taking care of my bug : (V 109.7)
I precise that this was working with the previous version 109.4 I had, it was working.

for the second point, I have a Postgres DB connected and so for **any** table of this DB , 
if I go to the dashbord , I get my data list correctly : 
![1-dashboard result](https://github.com/nocodb/nocodb/assets/6737060/ebf390dc-4f0a-4a6a-800f-ce8eabd66dd2)

and if I go to swagger I request without any filter , any parameter , just "try out" and "execute" : 
 
![2-swagger-execute](https://github.com/nocodb/nocodb/assets/6737060/b0b1e3b2-b6d9-43e1-8b7c-89b43aeea1a4)

I get the result : 
![2-swagger-result](https://github.com/nocodb/nocodb/assets/6737060/e3e24ae0-cfe2-4846-a100-152ee50a744e)
<div><div><h4>Server response</h4>

Code | Details
-- | --
Undocumented | TypeError: NetworkError when attempting to fetch resource.

**Comment by wingkwong** [comment] 2023-08-18 10:27
1. How do you install nocodb?
2. Which browser are you using?
3. Do you get the same error for other endpoints in swagger?
4. I noticed that you specified `xc-auth` and `xc-token` at the same time. Actually you just need either one.

**Comment by Productivix** [comment] 2023-08-18 11:01
1. I install nocodb in node from my own seed : https://github.com/Productivix/nocodb-seed-1 because your original seed was used to be 1 or 2 versions late, may be not good...see the package.json of today , I upgraded nocodb and express (!) : I will decrease to your version and test again and tell you.
2. using FireFox for Linux, last version, I do not think that is the issue,
3. yes same error for other tables (so same endpoint ?) of the same database
4. I did not know it was one of the 2 , I thought I need the 2 - but with one it is the same bug - thank you for the info.

**Comment by Productivix** [comment] 2023-08-18 11:37
I found the solution : it is just because I did not change the url to the custom one : https instead of http !
sorry  - I recommend since that when we start swagger from the app to get a swagger in the same url start , I mean if I start from "https..." I get a "https..." url.
![Capture d’écran_2023-08-18_13-34-02](https://github.com/nocodb/nocodb/assets/6737060/c5bff459-5f97-4d4f-960d-98253c552705)

so seed works with last express and nocodb versions - sorry

**Comment by wingkwong** [comment] 2023-08-18 12:13
@Productivix So the issue has been resolved in latest version right? 

I don't get the part `if I start from "https..." I get a "https..." url.`. Can you elaborate it more? I've tested the following cases.

- when my app is using http, the swagger is using http, the curl command is also using http
- when my app is using https, the swagger is using https, the curl command is also using https

**Comment by Productivix** [comment] 2023-08-18 13:16
to make it work I have to add a "s" in the custom Url

**Comment by wingkwong** [comment] 2023-08-18 13:18
Ok. As this's resolved in the latest version, this issue can be closed.

**Closed by wingkwong** 2023-08-18 13:18 UTC

**Comment by Productivix** [comment] 2023-08-18 13:20
yes the original issue but not the swagger https issue : do I need to write another issue ?

**Comment by wingkwong** [comment] 2023-08-18 13:22
You may create a new one. I couldn't reproduce it though.
