### ISSUE TITLE
🐛 Bug: Node v19.9.0

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#5782] opened 2023-05-31 17:39 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

"TypeError: Cannot read properties of undefined (reading '_noco')"

after update nocodb (node.js 19.9.0)

<img width="794" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/573aeefe-9e39-49cb-80b7-e9e122949deb">

<img width="915" alt="image" src="https://github.com/nocodb/nocodb/assets/5435402/66ba494c-23a0-4158-80a2-e050c532fb80">

### Desired Behavior

.

### Project Details

0.107.5+

**Comment by pranavxc** [comment] 2023-05-31 17:45
Duplicate of #5778

**Closed by pranavxc** 2023-05-31 17:45 UTC
