### ISSUE TITLE
🐛 Bug: form-view mode Attachment failed to upload

### ISSUE THREAD

**Issue by ninjagang** [nocodb/nocodb#5470] opened 2023-04-14 08:41 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

when i choose grid mode，Attachment upload successed。
i choose form mode and shareview，Attachment upload failed。

### Desired Behavior

please fix bug，so i can shareview with form mode

### Project Details

nocodb linux x64 single file

### Attachments

![1](https://user-images.githubusercontent.com/34408821/231991958-a75c6ad2-6d16-4402-9874-25067023d53d.png)
![2](https://user-images.githubusercontent.com/34408821/231991998-b716fce2-b743-4415-bbf4-90b5038a2f3e.png)

**Comment by wingkwong** [comment] 2023-04-14 09:35
Duplicate of https://github.com/nocodb/nocodb/issues/5434. A fix is being reviewed at this moment [here](https://github.com/nocodb/nocodb/pull/5454).

**Closed by wingkwong** 2023-04-14 09:35 UTC
