### ISSUE TITLE
🐛 Bug: Text disappears while typing because of autosave.

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#4146] opened 2022-10-21 13:50 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

**Precondition:**
Create a table with LongText field

**Steps to reproduce:**
1. Start typing any text in LongText field
2. Continue typing while "Loading..." message appears at top right corner

**Actual behaviour:**
Some letters disappear that were typed while "Loading..." message 

**Expected behaviour:**
You can continue typing without any problem during autosave

**Video:**
https://records.cherishdev.com/conversations/20d06372-d362-51a7-b04b-1bf006d7b0ee

### Desired Behavior

You can continue typing without any problem during autosave

### Project Details

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **true**
RootDB: **mysql2**
PackageVersion: **0.98.1**

**Comment by bcakmakoglu** [comment] 2022-10-21 13:52
Duplicate of #4103

**Closed** 2022-10-22 03:49 UTC

**Comment by stepheljobs** [comment] 2022-11-08 07:22
This is a major bug for me, because my users are having a hard time because they keep having to type the same thing over and over again. My suggestion is to save the text only if the focus from the cell was move away.

**Comment by alprotasov** [comment] 2022-11-08 08:28
@stepheljobs it was fixed. What version do you have?
