### ISSUE TITLE
🐛 Bug: Expert a string but recevied an array 

### ISSUE THREAD

**Issue by origyn-admin** [nocodb/nocodb#4589] opened 2022-12-02 14:23 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Upload XLS or XLSX to import a new table from URL

We obtain : Expert a string but recevied an array 

### Desired Behavior

imported data from XLS from an URL

### Project Details

NocoDB  version : 0.100.2

**Comment by wingkwong** [comment] 2022-12-02 14:51
Please provide a sample URL for reproducing the issue.

**Comment by wingkwong** [comment] 2023-01-07 04:07
Closing due to no feedback from user.

**Closed by wingkwong** 2023-01-07 04:07 UTC
Labels: 🐛 Type: Bug, 🔎 Status: More Info Needed
