### ISSUE TITLE
When I create a new form and find that the field properties are incorrect, I can't change them.

### ISSUE THREAD

**Issue by superigbt** [nocodb/nocodb#2202] opened 2022-05-30 08:05 UTC
**When I create a new form and find that the field properties are incorrect, I can't change them.**

Copy and Paste Project Info - Tutorials: How to check my Project info? ([YouTube Tutorial](https://www.youtube.com/watch?v=AUSNN-RCwhE) or [Documentation](https://docs.nocodb.com/FAQs#how-to-check-my-project-info-))

```
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.90.5**
```

or provide the following info

```
NocoDB used as docker : true / false
NocoDB version : 
Database used in NC_DB URL  : mysql | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
Project was created  by clicking : New Project | New Project by connecting to external database
Database on which spreadsheet is created : mysql | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
OS on which NocoDB is running : 
Node.js version if running as node : 
Database version : 
```

**Steps To Reproduce**

3. See error

**Expected Behavior**

**Screenshots**

Join our discord : https://discord.gg/5RgZmkW for realtime help.

**Comment by o1lab** [comment] 2022-05-30 08:11
Did you mean changing types within a form view ?

**Comment by superigbt** [comment] 2022-05-31 09:23
> 

yes

**Comment by wingkwong** [comment] 2022-07-02 08:39
@superigbt Can you record a video to show the problem? Just tested and they could be changed as expected.

![image](https://user-images.githubusercontent.com/35857179/176993343-c043189f-260f-4f75-bff9-7306817d7018.png)

![image](https://user-images.githubusercontent.com/35857179/176993352-487f026d-6ade-4183-82f3-3b45172d091c.png)

**Comment by cassbonin** [comment] 2022-08-13 12:22
I also have the same problem: when I create a form and then add a new field, the changes are not reflected in the form. After checking the API calls, I could not find any problem because the functions return 200.

frontend call to
/api/v1/db/meta/views/vw_8xex1c8fj04cq1/columns 
returns 200

But when I refresh the same page, the field still appears in the left panel to be added.
![image](https://user-images.githubusercontent.com/6727483/184493822-4d3c1942-68c7-452d-ac71-ad9c1e6e2c92.png)

**Comment by wingkwong** [comment] 2023-01-07 04:35
Closing - Just tested on the latest version (0.100.2) and couldn't reproduce the above 2 issues.

**Closed by wingkwong** 2023-01-07 04:35 UTC
Labels: 🔎 Status: More Info Needed
