### ISSUE TITLE
webhook url settings saved options not loaded on page reload even if it saved

### ISSUE THREAD

**Issue by yulduck** [nocodb/nocodb#904] opened 2022-01-03 03:53 UTC
NocoDB used as docker : tfalse
NocoDB version : 0.83.8
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : linux
Node.js version if running as node : 16.0.0
Database version : mariadb 10.3

**Steps To Reproduce**
1. create a webhook url on Automations menu. write down url and body that you want to send to the url.
2. Reload the page and  Go to 'Automations'
3. Click on the webhook option control left side of title that you created before.
4. url, body are not showing even if you saved them.

**Expected behavior**
saved webhook settings loaded correctly

**Comment by pranavxc** [comment] 2022-01-05 06:22
It's fixed in the latest version `0.84.1`

**Comment by pranavxc** [comment] 2022-01-05 06:23
Duplicate of https://github.com/nocodb/nocodb/issues/866

**Closed by pranavxc** 2022-01-05 06:23 UTC
