### ISSUE TITLE
🐛 Bug: date cell copy paste related

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7183] opened 2023-12-07 10:42 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Copy paste doesn't work for following format date cell (date tried was 20 Dec 2023). PG was root DB
- `DD-MM-YYYY`
- `DD/MM/YYYY`
- `DD MM YYYY`
- `YYYY MM` (source cell had `2023 05`; after paste, `2023 01` was displayed)

Error
```
index.ts:917 Error: Not a valid date
    at convertCellData (convertCellData.ts:64:17)
    at HTMLDocument.handlePaste (index.ts:855:30)
```

Issue is noticed with dateTime cell as well

### Desired Behavior

copy paste contents appropriately

### Project Details

202.9 + wkw DD YYYY PR (issue noticed in develop as well)

**Comment by gauravruhela07** [comment] 2023-12-08 03:12
@dstala @wingkwong I want to work on this issue, can you please assign it to me? Thank you.

**Comment by wingkwong** [comment] 2023-12-08 03:48
@gauravruhela07 I'm working on it. Please ask for those issues with no assignees instead.

**Comment by wingkwong** [comment] 2023-12-12 06:21
@dstala I couldn't reproduce in develop branch. Have you run `pnpm run bootstrap` first?

**Comment by harijoe** [comment] 2024-01-24 15:01
I confirm the bug exists on 0.204.0

<img width="316" alt="image" src="https://github.com/nocodb/nocodb/assets/10897494/ab5d0489-976e-47d1-94bf-7bc1e685b1da">

For example it happens when the date field format is set to DD-MM-YYYY (e.g. french notation).

**Comment by wingkwong** [comment] 2024-01-24 15:47
@harijoe which version and browser are you using?

**Closed** 2024-02-09 01:26 UTC
Labels: 🐛 Type: Bug
