### ISSUE TITLE
🐛 Bug: ERROR: Offset is beyond the total number of records

### ISSUE THREAD

**Issue by merewind** [nocodb/nocodb#7561] opened 2024-02-05 16:21 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

in the view - go to the last screen and type in the search box 

### Desired Behavior

no error

### Project Details

docker: true
ver:  0.204.0
on-prem setup 

### Attachments

![image](https://github.com/nocodb/nocodb/assets/25484042/d20200f4-a15c-4b27-b707-9d7f615e3527)

**Comment by rameshmane7218** [comment] 2024-02-05 19:08
Duplicate of #7501

**Closed** 2024-02-06 03:18 UTC
