### ISSUE TITLE
🐛 Bug: Content of columns with LongText is not visible with Microsoft Edge Dev

### ISSUE THREAD

**Issue by nilsreichardt** [nocodb/nocodb#5190] opened 2023-02-22 13:49 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Download Microsoft Edge Dev
2. Open NocoDB with Chrome
3. Fill a column of the type LongText with data
4. Open NocoDB with Microsoft Edge Dev
5. Try to read the column with the type LongText

### Desired Behavior

I would like to see the content of the columns.

### Project Details

NocoDB
```
Node: **v16.13.2**
Arch: **x64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.105.3**
```

Edge: Version 111.0.1660.13 (Official build) Dev(arm64)

### Attachments

At the top you can see Microsoft Edge and at the bottom you see Chrome.

https://user-images.githubusercontent.com/24459435/220639008-3271ea68-5162-4182-a643-2933ba2b7d7b.mp4

**Comment by o1lab** [comment] 2023-02-22 13:50
Hey @nilsreichardt, can you please help make a PR ?

**Comment by nilsreichardt** [comment] 2023-02-22 13:52
Hey @o1lab, thanks for your prompt reply! I would love to help 💙 However, I'm not in to web dev (I'm more in app dev) and currently don't have the time dig deep into the NocoDB codebase 😔

**Comment by o1lab** [comment] 2023-02-22 13:54
Ah np, I remembered your custom migration script & conversation. Hence the ask :)

**Comment by dstala** [comment] 2023-02-23 07:11
Treid, but couldn't reproduce it locally. Any specific version of edge dev?

![Screenshot 2023-02-23 at 12 39 43 PM](https://user-images.githubusercontent.com/86527202/220840795-4a5b6c12-fc84-4454-bd3b-26219cf35a7f.png)

**Comment by nilsreichardt** [comment] 2023-03-02 10:43
@dstala I can't reproduce anymore 🤔

**Comment by dstala** [comment] 2023-03-02 11:10
some change on either NocoDB or EdgeDev would have fixed it likely. will close this issue for now. Reopen if you notice it still.

**Closed by dstala** 2023-03-02 11:10 UTC
Labels: 🔎 Status: More Info Needed
