### ISSUE TITLE
Docker failing on Apple with M1 chip

### ISSUE THREAD

**Issue by go4cas** [nocodb/nocodb#249] opened 2021-06-08 11:54 UTC
When starting a nocodb Docker container, on an Apple MackBook with M1 (ARM64) chip, I get the following:
"**_The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested_**".

**Comment by maxnatt** [comment] 2021-06-08 21:48
Duplicate of the https://github.com/nocodb/nocodb/issues/183.

**Comment by azrikahar** [comment] 2021-06-14 08:58
@go4cas Hi, I've recently tried to help out and created an arm64 variant of nocodb image over at https://hub.docker.com/r/azrikahar/nocodb. Would you mind helping to test whether it works for you? After that we will be able to merge it into nocodb officially

**Comment by go4cas** [comment] 2021-06-14 13:10
@azrikahar ... it is working 100%! Thank you very much!!

**Closed** 2021-06-19 12:56 UTC
Labels: enhancement

**Comment by Hu-Wentao** [comment] 2023-01-16 18:01
replace `image: "mysql:5.7"`to `image: "mariadb:10.5.8"`
because mysql 5.7 not support arm64/v8
