### ISSUE TITLE
🐛 Bug: Drag and drop item in calendar doesn't work

### ISSUE THREAD

**Issue by alprotasov** [nocodb/nocodb#9360] opened 2024-08-27 22:23 UTC
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

1. Create a calendar view
2. Drag and Drop any item between two dates

**AR:** Changes were not applied and error appears
https://berrycast.com/conversations/ca339a0f-caf0-556d-a75c-941a54a5c431
**ER:** Date updated

### Desired Behavior

Date updated

### Project Details

Node: **v20.15.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.255.0**

**Comment by dstala** [comment] 2024-08-28 04:32
@alprotasov calendar will be in RO mode if you have created calendar using NocoDB system field (createdAt / updatedAt). 

@DarkPhoenix2704 to map appropriate error if that is the case instead of displaying SQL error

**Comment by alprotasov** [comment] 2024-08-28 07:17
https://berrycast.com/conversations/1a5fcd70-845b-5fdc-aae3-99a0b2607906

**Comment by DarkPhoenix2704** [comment] 2024-08-28 07:21
Can you share the mysql version. I just tried locally and couldn't reproduce

**Comment by alprotasov** [comment] 2024-08-28 07:24
db:
    image: mysql:5.7

**Comment by DarkPhoenix2704** [comment] 2024-08-28 07:49
We include the timezone info along with the Date.  This format is added in Mysql 8.

So previous versions of mysql will break


Ref.  https://stackoverflow.com/a/73686992/14265665

**Closed** 2024-08-28 14:07 UTC
Labels: 🐛 Type: Bug
