### ISSUE TITLE
🐛 Bug: email verification not working

### ISSUE THREAD

**Issue by asaage** [nocodb/nocodb#7473] opened 2024-01-21 16:12 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

When inviting new users to a workspace the verify Email is being sent
but the link responds 404 ```{"msg":"Cannot GET /email/verify/email_verification_token"}```

### Desired Behavior

should verify sucessfully...
On the other hand - in case of invitation i would prefer to skip this entirely and go on with setting a password for the new user.

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.204.0**

**Comment by opokhvalit** [comment] 2024-01-23 12:55
I can confirm that behavior. NocoDB sent incorrect invite and verification links.
For invite I've got link like:
`//dashboard#/signup/<ID>`
but correct link must looks like:
`/dashboard/#/signup/<ID>`

The similar thing for email verification link, I've got
`//email/verify/<ID>`
but proper link must looks like 
`/#/email/verify/<ID>`

**Comment by opokhvalit** [comment] 2024-01-23 13:53
I fixed partially my issues
1. for NC_PUBLIC_URL we should NOT put trailing slash
2. for NC_DASHBOARD_URL we must put trailing slash
So, that will resolve invite link issues

Email verification link issue is still present. I really didn't get nesessity of email verification and didn't find where that confirmation marked as done

**Comment by SteffeyDev** [comment] 2024-02-19 19:47
I'm seeing same issue, when user tries to verify email, they are redirected to a page that shows `{"msg":"Cannot GET /email/verify/602dc059-66c3-45d6-8b96-f0261ccbc259"}`. The link appears formatted correctly. I checked the DB and the `602dc059-66c3-45d6-8b96-f0261ccbc259` does match their user in the `email_verification_token` column in the `nc_users_v2` table. Using docker `:latest`.

Full error output:
```
[Nest] 11  - 02/19/2024, 7:36:39 PM   DEBUG [GlobalExceptionFilter] NotFoundException: Cannot GET /email/verify/602dc059-66c3-45d6-8b96-f0261ccbc259
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
```

**Closed** 2024-06-05 07:55 UTC
