### ISSUE TITLE
Rename table and project

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#2749] opened 2022-07-20 08:05 UTC
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.92.4**

**Steps To Reproduce**

rename table
1. rename sheet1 to sheet111.
2. create new table sheet1.  it can't create the table，“Duplicate table name”.
3. The table name has not changed in the database.

 rename project
1. edit project，change the name.
2. the project name has not changed in the database.

bty
delete project doesn't delete the project in the database, 
but when i create a project with the same name, 
it can read the original data. Maybe this can not be resolved.

**Expected Behavior**

resolve the problem of rename.

**Screenshots**

![image](https://user-images.githubusercontent.com/42569476/179929329-19e57837-c42c-48b6-ad0a-08e689712402.png)

**Comment by wingkwong** [comment] 2022-07-20 08:30
1. Rename Table - Same as https://github.com/nocodb/nocodb/issues/2668 - Fix is in progress
2. Rename Project - Couldn't reproduce - are you talking about `nc_projects_v2.title` not being changed?
3. Delete Project - Couldn't reproduce - what do you mean by  `delete the project in the database`? 

For 2 & 3, if possible, please provide a video for demonstration. Thanks.

**Comment by whyteserious** [comment] 2022-07-21 03:22
For 2&3, I understand this operation and idea, and there is no need to modify it.
Thanks.

**Closed** 2022-07-21 03:23 UTC

**Comment by whyteserious** [comment] 2022-07-29 02:49
For 3, maybe you can add an option to delete from the database.
