### ISSUE TITLE
🐛 Bug: Updating user permissions 

### ISSUE THREAD

**Issue by lsoldado** [nocodb/nocodb#4684] opened 2022-12-21 23:32 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

If i had an user with viewer permissions, it will not upload any docs (that´s ok).
But if i change permissions to editor, that user need to logout and login to assume that permission.
But if the user logout again it will loose the editor permission and goes to viewer again.

### Desired Behavior

Changing permission correctly

### Project Details

NocoDb as Docker
Version: 0.100.2

### Attachements

![Screenshot_2022-12-20_at_15 36 45](https://user-images.githubusercontent.com/22603486/209022547-78a4ea1d-5ea5-4daf-8813-f44277a9c144.png)

**Comment by pranavxc** [comment] 2022-12-26 08:49
Are you changing the roles at the project level or the global level?

**Comment by lsoldado** [comment] 2022-12-26 11:59
Hi, project level

**Comment by pranavxc** [comment] 2023-01-16 07:53
Can you check our latest release, looks like duplicate of 4699

**Comment by pranavxc** [comment] 2023-01-23 09:49
Closing since already fixed and duplicate of #4699. Feel free to open if you still facing the issue.

**Closed by pranavxc** 2023-01-23 09:49 UTC
