### ISSUE TITLE
Swagger API's not updated properly. 

### ISSUE THREAD

**Issue by BillMeyerRSA** [nocodb/nocodb#886] opened 2021-12-22 13:17 UTC
Low priority 
NocoDB used as docker : true
NocoDB version : 0.83.8
Database used in NC_DB URL  : mysql / mariadb
Project was created  by clicking : New Project by connecting to external database
OS on which NocoDB is running : Docker

Created Test table. Checked the Swagger API's.
Deleted the Test table. 
Did the Metadata Recreate
Reloaded. 

When I go to the Swagger API's the Test DB is still in the API. 
Tested it with list / post, and as expected it does not work. 
Had to restart docker containers to reflect deleted table in the Swagger API's.

**Comment by pranavxc** [comment] 2022-01-03 10:35
Duplicate of #866

**Closed by pranavxc** 2022-01-03 10:35 UTC
Labels: bug
