### ISSUE TITLE
vue3 : show all / hide all is not working

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3118] opened 2022-08-12 12:34 UTC
In grid view > fields menu

**Comment by wingkwong** [comment] 2022-08-20 11:01
Working fine on my side (base / share base / share view). Seems it has been resolved at some point.

**Comment by o1lab** [comment] 2022-08-20 11:03
Is resolved now.

**Comment by mertmit** [comment] 2022-08-21 09:08
Looks like duplicate of https://github.com/nocodb/nocodb/issues/3182 which is solved now

**Closed** 2022-08-21 10:00 UTC
Labels: Scope: vue3
