### ISSUE TITLE
🐛 Bug: Auto-upstall ends with message "docker: 'compose' is not a docker command."

### ISSUE THREAD

**Issue by DavidIsaacBPS** [nocodb/nocodb#10009] opened 2024-12-09 20:50 UTC
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

On AWS EC2 Linux:
* Install docker: sudo yum install docker -y; sudo systemctl start docker
* Run auto-upstall command

### Desired Behavior

Install should complete with success message

### Project Details

N/A

**Comment by sinanmohd** [comment] 2024-12-10 04:21
Duplicate of #10008

**Closed by sinanmohd** 2024-12-10 04:21 UTC
Labels: 🐛 Type: Bug
