### ISSUE TITLE
🐛 Bug: Tasks disappearing from view on status change

### ISSUE THREAD

**Issue by TobiasDax** [nocodb/nocodb#7051] opened 2023-11-21 16:26 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

On one of my tables if i change the status of an entry in a row the whole row disappears until i reload the page.
The change is saved, so everything seems to be working, just the row is vanishing.

https://github.com/nocodb/nocodb/assets/42605856/393546ad-636d-4b4c-b5ca-81eba8f0849d

### Desired Behavior

The row should stay visible while i work on it

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.5**

**Comment by pranavxc** [comment] 2023-11-22 05:48
Hi @TobiasDax, can you help me with following details, will be helpful to debug.

- What's the type of column which you had used for grouping ?
- Looks like you are using slightly older r=version, can you try with latest version as well.
- Is there any backend error log or browser console error ?

**Comment by dstala** [comment] 2023-11-22 16:22
tried by using single-select as grouping fields. couldn't reproduce issue

**Comment by TobiasDax** [comment] 2023-11-22 16:27
> Hi @TobiasDax, can you help me with following details, will be helpful to debug.
> 
> * What's the type of column which you had used for grouping ?
> * Looks like you are using slightly older r=version, can you try with latest version as well.
> * Is there any backend error log or browser console error ?

Hi,

- i used a singe selct field as a grouping filed
- will tell the it guy to update and then check in again ;)
- no console logs in my browser (thats why i had it open in the video) i will try and get my hands on some noco db logs.

sadly the error is only popping up sporadically so i cant reproduce it safely myself. But it happens often enough to be quite the inconvenience

**Comment by pranavxc** [comment] 2023-11-22 18:39
> > Hi @TobiasDax, can you help me with following details, will be helpful to debug.
> > 
> > * What's the type of column which you had used for grouping ?
> > * Looks like you are using slightly older r=version, can you try with latest version as well.
> > * Is there any backend error log or browser console error ?
> 
> Hi,
> 
> * i used a singe selct field as a grouping filed
> * will tell the it guy to update and then check in again ;)
> * no console logs in my browser (thats why i had it open in the video) i will try and get my hands on some noco db logs.
> 
> sadly the error is only popping up sporadically so i cant reproduce it safely myself. But it happens often enough to be quite the inconvenience

Try after the upgrade and if it still persist let's have a call. You can ping me in our discord channel : https://discord.gg/5RgZmkW ( my discord id - pranavxc )

**Comment by dstala** [comment] 2023-12-19 12:03
@TobiasDax was this issue sorted out?

**Comment by dstala** [comment] 2024-01-13 10:33
closing this issue. if issue still persists in v204.0, please DM pranavxc on discord https://discord.gg/5RgZmkW

**Closed by dstala** 2024-01-13 10:33 UTC
Labels: 👩‍🔬 Status: In-Analysis
