### ISSUE TITLE
🐛 Bug: M2M tables without content after update

### ISSUE THREAD

**Issue by j-stahl** [nocodb/nocodb#7158] opened 2023-12-05 10:44 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Hard to say, if you can really reproduce it. It is a migration problem.

I have 2 tables named `images` and `products` with a M2M connection between them. After upgrading from NocoDB 0.96.4 the first view on the data looks great. On a deeper look, I realised the column with the m2m table is empty in both tables.
![grafik](https://github.com/nocodb/nocodb/assets/15193774/3ac94b13-22b7-45ac-b83a-f333bab71de2)

While NocoDB obviously knows, there are links. On clicking the plus button for adding new linked records, I can see this:
![grafik](https://github.com/nocodb/nocodb/assets/15193774/af38f461-cd3a-4809-98d6-9704828b6227)

When I try to add data with the web interface, this is basically possible. The MySQL table shows new records appearing inside, but the result is not visible in the web frontend.

The HTTP Response from the server, shows there are empty objects for m2m tables, while another hm/bt table delivers object id's. The same result, I can see, when I use the REST API with my own app.
![grafik](https://github.com/nocodb/nocodb/assets/15193774/7e03d4ea-d164-44e7-b8d2-cf4288206e8f)

When I create a brand new test base with 2 test tables. The relations between both tables will be shown correctly. In the linked column appears an information. Which means basically the new software seems to work properly on new bases and tables.
![grafik](https://github.com/nocodb/nocodb/assets/15193774/960cd39b-9644-4fc2-95df-452716368b4c)

I have only this one M2M relation between the tables and I want to repair it. Sadly I do not know how NocoDB realizes the relations, and where I can start search for the source of this issue.

### Desired Behavior

After the NocoDB update the data should be migrated correctly and be available in the view in the same way new created data is.

### Project Details

Node: **v18.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.202.9**

**Comment by pranavxc** [comment] 2023-12-05 18:22
We had made a fix, please try the following PR build to verify the fix.

```
docker run -d -p 8888:8080 nocodb/nocodb-timely:0.202.9-pr-7161-20231205-1350
```

**Comment by pranavxc** [comment] 2023-12-05 18:24
Duplicate of #7125

**Closed by pranavxc** 2023-12-05 18:24 UTC

**Comment by j-stahl** [comment] 2023-12-08 12:25
YES! That's it. Good work.
The image you mentioned worked for me.

When do you expect the next official release containing this fix?
