### ISSUE TITLE
🐛 Bug: Docker-Upgrade to 0.251.1 causes trouble again

### ISSUE THREAD

**Issue by WeT-Klb** [nocodb/nocodb#8922] opened 2024-07-03 15:46 UTC
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I just upgraded from my working installation to 0.251.1 - but the container won't start because of this error:

`Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
nc_054_id_length: Replaced long base IDs in 0.004665719s
nc_054_id_length: Altered nc_api_tokens.base_id to 20 characters in 0.119606822s
migration file "nc_054_id_length" failed
migration failed with error: alter table `nc_audit_v2` modify `base_id` varchar(20) - Data too long for column 'base_id' at row 231
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [NestFactory] Starting Nest application...
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] PassportModule dependencies initialized +2ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 8  - 07/03/2024, 3:37:43 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +2ms
[Nest] 8  - 07/03/2024, 3:37:43 PM   ERROR [ExceptionHandler] alter table `nc_audit_v2` modify `base_id` varchar(20) - Data too long for column 'base_id' at row 231
Error: alter table `nc_audit_v2` modify `base_id` varchar(20) - Data too long for column 'base_id' at row 231
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/usr/src/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/usr/src/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/usr/src/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode `(node:internal/streams/readable:510:3)``

### Desired Behavior

The container just should work.

### Project Details

NocoDB as docker on QNAP-TS251 with MariaDB.

**Comment by mertmit** [comment] 2024-07-03 20:28
It looks like there is an old audit entity which have base_id field >20 char. We handle all long base_id's in nc_bases_v2 so somehow those rows doesn't have a corresponding base on that table.

If possible lets figure out that problematic base_id to get an idea how & why this happened using following query:

```
SELECT base_id FROM nc_audit_v2 WHERE CHAR_LENGTH(base_id) > 20;
```
If possible share response of this query with us.

For next steps we will either modify those with a proper base_id or we will get rid of from those rows.

**Comment by WeT-Klb** [comment] 2024-07-04 05:09
Hi,

this is the result:

![NocoDB](https://github.com/nocodb/nocodb/assets/20600342/59eb6975-b550-45f8-b763-cfbfda19434d)

**Comment by sre-daniel-ioki** [comment] 2024-07-04 07:18
We run into the same problem while upgrading from 0.251.0 to 0.251.1. 

We run nocodb in docker with an sqlite database. 

<details><summary>Logs</summary>

```
(node:3) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
nc_054_id_length: Replaced long base IDs in 0.000865607s
nc_054_id_length: Altered nc_api_tokens.base_id to 20 characters in 0.020904068s
nc_054_id_length: Altered nc_audit_v2.base_id to 20 characters in 0.012206872s
nc_054_id_length: Altered nc_base_users_v2.base_id to 20 characters in 0.007782275s
nc_054_id_length: Altered nc_columns_v2.base_id to 20 characters in 0.015402401s
migration file "nc_054_id_length" failed
migration failed with error: ROLLBACK TO SAVEPOINT trx13 - SQLITE_ERROR: no such savepoint: trx13
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [NestFactory] Starting Nest application...
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 3  - 07/04/2024, 7:04:23 AM   ERROR [ExceptionHandler] ROLLBACK - SQLITE_ERROR: cannot rollback - no transaction is active
Error: ROLLBACK - SQLITE_ERROR: cannot rollback - no transaction is active
```

</details>

**Comment by mertmit** [comment] 2024-07-08 10:17
Hi @WeT-Klb sorry for being late to respond, we are planning to have a fix for this on our next release.
This issue is caused bc of leftover comments for base with long id.

You only have 2 problematic audit records (getting rid of them would cause no trouble) so if you don't want to wait for next release & quickly migrate you can use following query:
```
DELETE FROM nc_audit_v2 WHERE CHAR_LENGTH(base_id) > 20;
```
This will delete these records from your audit table.

Feel free to ask if you have any concerns.

**Comment by WeT-Klb** [comment] 2024-07-08 11:22
Hi, thanks for your support - i followed your advice and it worked.

But still found one problem:

Only when I sign in to NocoDB, open a database and log out I will get this screen:

![Screen 1](https://github.com/nocodb/nocodb/assets/20600342/5b2821d1-f055-418d-9a89-92167a65e62f)

If I only log in and log out again that red message won`t be shown.
It only appears when i open the table in NocoDB.

**Comment by mertmit** [comment] 2024-07-08 11:31
This is not seem to be reproducible on my side, what is the org role of the account you are using (as well as base role)?
Also can you please check your developer console (Right-click > inspect or F12 & go to console tab) to see if there are any errors available or you can find the failing request in Network tab (should have red text), clearly one of the requests fails with 403 but it would be really helpful to know which one.

**Comment by WeT-Klb** [comment] 2024-07-08 12:00
I try to pass the infos:

Anforderungs-URL:
http://192.168.1.241:9092/api/v1/auth/user/signout
Anforderungsmethode:
POST
Statuscode:
403 Forbidden
Remoteadresse:
XXX.XXX.XXX.XXX:port   (Masked)
Referrer-Richtlinie:
strict-origin-when-cross-origin

Access-Control-Allow-Origin:
*
Connection:
keep-alive
Content-Length:
21
Content-Type:
application/json; charset=utf-8
Date:
Mon, 08 Jul 2024 11:52:35 GMT
Etag:
W/"15-w2iWSrrtAMKbcMtwWsXx7NvsCrQ"
Keep-Alive:
timeout=5
X-Powered-By:
Express

Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate
Accept-Language:
de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection:
keep-alive
Content-Length:
0
Cookie:
PHPSESSID=tloa0jch9lu7puccp9450kceh6; NAS_PW_STATUS=0; NAS_USER=admin; home=1; CS_TOKEN=y3ylg66m; QT=1720437854590
Dnt:
1
Host:
XXX.XXX.XXX.XXX:Port
Origin:
XXX.XXX.XXX.XXX:Port
Referer:
http://XXX.XXX.XXX.XXX:Port/dashboard/
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Xc-Gui:
true

![image](https://github.com/nocodb/nocodb/assets/20600342/8cee6788-6d66-48ba-885f-e1ed48f02c10)

**Comment by dstala** [comment] 2024-07-27 03:43
@mertmit see if the logs help

**Comment by WeT-Klb** [comment] 2024-08-15 14:46
Today i upgraded to 0.255.0 - now there is one sign more - maybe it can help?

![NocoDB Token](https://github.com/user-attachments/assets/e8bb2fc6-cb95-4438-ba81-561e1cf19fff)

**Comment by WeT-Klb** [comment] 2024-08-29 20:15
With 0.255.2 that sign don't appear anymore. So this case is done.

**Comment by WeT-Klb** [comment] 2024-08-31 07:54
Sorry to reopen again - but it still happens when I sign in to NocoDB, open one table and afterwards I sign off from NocoDB that sign with "Invalid Token" appears.
Like before it only happens when I open one table inside NocoDB. If I only sign in and directly sign off it won't appear.

**Closed** 2024-09-04 18:56 UTC
