### ISSUE TITLE
🐛 Bug: SignIn/SignUp -- trim extra spaces if any

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#8910] opened 2024-07-02 10:28 UTC
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

![Screenshot 2024-07-02 at 3 56 25 PM](https://github.com/nocodb/nocodb/assets/86527202/140e4ef2-c54f-43f4-87a8-8e1dfe3a31e8)

### Desired Behavior

trim extra space automatically

### Project Details

251.0

**Comment by yaten2302** [comment] 2024-07-04 07:31
@dstala, I was trying to replicate this issue, when I'm on the sign up page, there is no extra space, which I'm able to see?<br>
![image](https://github.com/nocodb/nocodb/assets/129659514/5abe1f5f-af0c-4d6c-b20b-91e4e0b421af)
<br>
Could you please guide that am I on the wrong page?

**Comment by dstala** [comment] 2024-07-08 07:01
@yaten2302 issue seen only in self hosted env

**Comment by yaten2302** [comment] 2024-07-09 04:57
Got it @dstala , I've successfully reproduced this issue in the my self hosted env.

Actually, I've a doubt, that to change something in the sign-in page, I've to make changes in this file - `nocodb/packages/nc-gui/pages/signin.vue`, am I right?

**Comment by yaten2302** [comment] 2024-07-09 05:28
Thanks for assigning this issue to me 👍 I'll try to fix this ASAP 👍

**Comment by yaten2302** [comment] 2024-07-09 17:57
Hey @dstala @rameshmane7218 , I was trying to fix this issue, but, I'm having a doubt:
In the formRules, I've changed the validateEmail(v) to validateEmail(v.trim()), but it's still showing the error?<br>
![image](https://github.com/nocodb/nocodb/assets/129659514/a9ae15cf-cd51-4079-b578-0fc00660bf6e)
<br>
![image](https://github.com/nocodb/nocodb/assets/129659514/e1a8e2c5-76a0-4050-bb14-a028c4cb2335)


![image](https://github.com/nocodb/nocodb/assets/129659514/cbb4cb77-61a7-420d-9fa1-a05cf9c549ab)


I wanted to ask that, could you please guide that is this error being shown due to this block of code:

![image](https://github.com/nocodb/nocodb/assets/129659514/7aca97de-67f1-4cf1-9a52-1bde0c0e8a62)

**Comment by yaten2302** [comment] 2024-07-12 10:53
@dstala @rameshmane7218 apologies for inconvenience, actually, I'm not able to view my changes after running the command - `pnpm start:backend`. After running this command, if I'm making any changes, those are not being shown in the browser. I've followed the steps as given in the [development setup](https://docs.nocodb.com/engineering/development-setup/). Can anyone please help me out with this. Here's a recording of my screen:

https://drive.google.com/file/d/14Cq5BzSB2Vv-HypxU9eohXpeYGFpD19z/view?usp=sharing

**Comment by yaten2302** [comment] 2024-07-19 13:14
Hey @dstala @rameshmane7218 , really sorry for the huge delay, actually, there was some issue with setting up this project on my device. I've created a [PR](https://github.com/nocodb/nocodb/pull/9031) for this issue, could you please review that and lmk if any changes are required.

**Closed** 2024-07-20 11:50 UTC
