### ISSUE TITLE
🐛 Bug: Linking failed: DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys

### ISSUE THREAD

**Issue by semighoti** [nocodb/nocodb#5915] opened 2023-06-17 13:51 UTC
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Create a 1-N relationship on Nocodb [or on Postgres itself] between table 1 and table 2
- Table 1 has many items on table 2
- Entering a value on any column on table 1 shows no error, and the value updated
- Entering a value on any column on table 2 show the error, but the value still updated.
- Drop the relationship and everything is back to normal
- There is no issue if N-N relationship created between 2 tables

### Desired Behavior

No error showed just like other relationship created with the database

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.109.1**

### Attachments

![Screenshot from 2023-06-16 10-26-18](https://github.com/nocodb/nocodb/assets/76666786/c4843384-2b36-49c2-ad34-a0abc1b709c9)

**Comment by dstala** [comment] 2023-06-18 02:31
Tried it out over a table created within NocoDB (SQLite meta table). Works just fine. 
Also tried connecting to an external PG database (sakila DB, on postgres version 14.7) - was able to add records sans error on both Country & City table (Country Has-Many City)

Are you connecting to external DB? If so, what is your PG version? This could be happening due to some additional conditions configured on your external DB for this column/relation.

Can you try and see if you see problem when you create a table with Has-many relation on default database (SQLite) in your case? This will help narrow down if issue is only with external DB connections.

**Comment by Sov3rain** [comment] 2023-06-26 12:38
Hey, I'm encountering the same issue. Here is my project details:

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.107.5**

Created a HasMany relation column and populated it. Now I can't update and/or delete the filled in columns.

I've got 2 pg database, one for metadata and one for the data itself.

I tried to create another project, import my data from my pg database and everything works well (even when the relationship is filled in).

**Comment by dtinth** [comment] 2023-07-10 21:19
I think I have a reproduction.

Here is the database file: [noco.db.zip](https://github.com/nocodb/nocodb/files/12008582/noco.db.zip)

Log in with:
```
root@example.com
password
```

This table has gotten into a bugged state:

<img width="1026" alt="image" src="https://github.com/nocodb/nocodb/assets/193136/aeb19e86-7ab4-4637-b5ac-ae90c4b2489d">

When you try to link an `Event` to a row in `SponsoredItems`, this error shows:

> Linking failed: DataLoader must be constructed with a function which accepts `Array<key>` and returns `Promise<Array<value>>`, but the function did not return a Promise of an Array of the same length as the Array of keys. Keys: 1 Values:

Now the row itself becomes very bugged — it is impossible to update the row or delete it.

Not sure if it helps with investigation, but at one point I wrongly created a LinkToAnotherRecord relation with "Many To Many". Once I realized the mistake, I deleted the column and recreated it with "Has Many" instead.

**Comment by pranavxc** [comment] 2023-07-12 07:13
@dtinth: I have attempted to reproduce the issue using the shared meta db, but I was not successful. Could you please provide any additional steps or information that might help me replicate the problem? And which version of NocoDB are you using ?


https://github.com/nocodb/nocodb/assets/61551451/4a84112e-80d9-4745-bec5-1831cec81832

----

@Sov3rain and @semighoti: Could you please share any additional error logs from the backend log? It would be helpful to see if there are any query-related errors or other bugs that might be occurring before the dataloader error. Providing these details will assist me in better understanding the issue and offering more precise suggestions. Thank you in advance!

**Comment by Sov3rain** [comment] 2023-07-12 08:02
The issue seems to be a bit random, I'll try to pin it and get some logs if I can. I'll get back to you.

**Comment by dtinth** [comment] 2023-07-12 11:58
@pranavxc My apologies. I tried loading the DB and indeed, the problem is no longer reproducable.

What I noticed is that the **problem is gone after I restart the NocoDB instance.** So… good news — the problem is transient. But bad news — no reproduction 😭.

**Comment by pranavxc** [comment] 2023-07-12 15:19
@dtinth @Sov3rain Thank you for your prompt response. I appreciate your input. I'm currently investigating the issue, and it seems that the root cause may vary for both of you. The error is triggered when the nested query fails, specifically the query to retrieve the mm, hm, and bt column data. If either of you encounter the issue again, please provide any additional backend logs that may be helpful in resolving the problem.

**Comment by dtinth** [comment] 2023-07-12 17:05
In my `noco.db` base file attached above, there should be an [audit log](https://docs.nocodb.com/setup-and-usages/audit/) that should list the changes that I’ve made to the database. Also the [ERD](https://github.com/nocodb/nocodb/assets/193136/733e93c1-ad57-46c4-b8b5-5143ea359d37) might help in following along with the audit log. However, I currently don’t have the capacity to verify that following the steps would result in a successful reproduction (sorry).

I was running from source. Commit is 844fec694, which corresponds to the tag [`0.109.3`](https://github.com/nocodb/nocodb/releases/tag/0.109.3).

**Comment by francoaguerre22** [comment] 2023-07-21 13:55
Hello, i'm having the same issue and i don't know if this is solved yet.

I think the bug is caused by using many to many relations in some tables, after a while using it when i try to download the table or try to insert/update a record this message is showed.

DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys. Keys: 2,11 Values:

In this case i think those keys: 2,11 are the ones making this bug happen. At some point y managed to solve this by deleting the table that has a many to many relation, but in this particular case, there are no many to many relations in this project and i still can´t download the table

These are my project details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
![Captura desde 2023-07-21 10-51-37](https://github.com/nocodb/nocodb/assets/140177921/c711e24d-66c6-43c1-a1e8-6fefd828a3da)

RootDB: **mysql2**
PackageVersion: **0.107.5**

**Comment by pranavxc** [comment] 2023-07-22 05:03
@francoaguerre22 Can you share the backend logs? It will help us to figure out the actual reason.

**Comment by dstala** [comment] 2023-10-27 11:14
please reopen this thread if you still see issue persist with latest release

**Closed by dstala** 2023-10-27 11:14 UTC
Labels: 🔎 Status: More Info Needed
